import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
import {advisorSummary,simulate,priorityDraft,applyReviewedPriority,planningTools} from '../server/advisor.ts';
function fixture(){const s=C.fresh();s.name='Do not send owner name';s.accounts=[{id:'private-bank-id',name:'Do not send bank name',kind:'asset',currency:'CNY',opening:100000,baselineDate:'2026-10-06',baselineSeq:0}];s.notes=[{id:'private-note',title:'Do not send note',body:'Private text',items:[]}];s.goals=[{id:'private-goal',name:'Do not send goal name',target:200000,priority:1}];s.reservations={'private-goal':0};s.categories=[{id:'food',name:'Food',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:100000,alloc:{food:10000},locks:{}}];return s;}
test('advisor summaries exclude owner names, account identities, notes and raw history',()=>{const summary=advisorSummary(fixture()),text=JSON.stringify(summary);assert.ok(!text.includes('Do not send'));assert.ok(!text.includes('private-bank'));assert.ok(!text.includes('private-goal'));assert.ok(!text.includes('Private text'));assert.equal(summary.goals[0].alias,'G1');assert.equal(summary.goals[0].target,200000);assert.equal(summary.cash.cash,100000);});
test('planning tools use the engine and never mutate their source records',async()=>{const s=fixture(),old=C.clone(s),p=simulate(s,{mode:'budget',extraCost:'0',incomeChange:'0',protectedSaving:'0'});assert.equal(p.recordsChanged,false);assert.equal(p.results[0].goal,'G1');assert.equal(p.results[0].name,undefined);const tools=planningTools(s);assert.deepEqual(Object.keys(tools),['simulate_plan','propose_goal_priority']);const draft=await tools.propose_goal_priority.execute({goal:'G1',priority:2});assert.equal(draft.reviewRequired,true);assert.deepEqual(s,old);});
test('a proposal needs review and becomes stale after any workspace change',async()=>{const s=fixture(),draft=await priorityDraft(s,{goal:'G1',priority:2});await assert.rejects(applyReviewedPriority(s,draft),/Review/);const changed=C.mutate(s,'note',{},n=>n.notes[0].body='new');await assert.rejects(applyReviewedPriority(changed,draft,true),/changed/);const applied=await applyReviewedPriority(s,draft,true);assert.equal(applied.goals[0].priority,2);assert.equal(s.goals[0].priority,1);assert.equal(applied.operations.length,1);await assert.rejects(applyReviewedPriority(applied,draft,true),/changed/);});
test('tool parsing rejects injected actions, floating money and archived goals',async()=>{const s=fixture();assert.throws(()=>simulate(s,{mode:'budget',extraCost:'1.001',incomeChange:'0',protectedSaving:'0'}),/decimal/);assert.throws(()=>simulate(s,{mode:'budget',extraCost:'0',incomeChange:'0',protectedSaving:'0',execute:'anything'}),/input/);await assert.rejects(priorityDraft(s,{goal:'G1',priority:0}),/priority/);s.goals[0].archived=true;await assert.rejects(priorityDraft(s,{goal:'G1',priority:2}),/active/);});
test('tools cannot disclose or propose edits to goals outside the approved summary',async()=>{const s=fixture();s.goals=Array.from({length:51},(_,i)=>({id:`g${i}`,name:`Private goal ${i}`,target:100,priority:i+1}));s.reservations=Object.fromEntries(s.goals.map(g=>[g.id,0]));const summary=advisorSummary(s),simulation=simulate(s,{mode:'budget',extraCost:'0',incomeChange:'0',protectedSaving:'0'});assert.equal(summary.goals.length,50);assert.equal(summary.goalsOmitted,1);assert.equal(simulation.results.length,50);assert.ok(!JSON.stringify(simulation).includes('G51'));assert.ok(!JSON.stringify(simulation).includes('Private goal'));await assert.rejects(priorityDraft(s,{goal:'G51',priority:1}),/approved summary/);});
