import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {worstCaseCost,budgetedAdvisor} from '../server/advisor-budget.mjs';
const config={provider:'Synthetic API',model:'Synthetic model',supportedFinanceTraffic:true,priceCheckedAt:new Date().toISOString(),maxInputTokens:1000,maxOutputTokens:500,maxSteps:2,inputMicroUsdPerMillion:1000000,outputMicroUsdPerMillion:2000000,fixedMicroUsdPerStep:100};
const hash=createHash('sha256').update(JSON.stringify(config)).digest('hex'),workspaceDigest='b'.repeat(64),summaryDigest=createHash('sha256').update(JSON.stringify({currency:'CNY'})).digest('hex'),promptDigest=createHash('sha256').update('What can I afford?').digest('hex');
function fixture(status='reserved'){const calls=[],ledger={reserve:async value=>{calls.push(['reserve',value]);return {status};},settle:async value=>calls.push(['settle',value])},generate=async value=>{calls.push(['generate',value]);return {result:'Synthetic result',chargedMicroUsd:100};},request={owner:crypto.randomUUID(),requestId:crypto.randomUUID(),workspaceDigest,summaryDigest,consent:{confirmed:true,provider:config.provider,model:config.model,workspaceDigest,summaryDigest,promptDigest,configurationHash:hash},summary:{currency:'CNY'},prompt:'What can I afford?'};return {calls,ledger,generate,request};}
const run=f=>budgetedAdvisor({ledger:f.ledger,generate:f.generate,configuration:config,configurationHash:hash});
test('worst-case charges use exact USD units, token limits, steps and explicit fees',()=>{assert.equal(worstCaseCost(config),4200);assert.equal(worstCaseCost({...config,maxInputTokens:1,maxOutputTokens:1,maxSteps:1,inputMicroUsdPerMillion:1,outputMicroUsdPerMillion:1,fixedMicroUsdPerStep:0}),1);assert.throws(()=>worstCaseCost({...config,outputMicroUsdPerMillion:undefined}),/price/);assert.throws(()=>worstCaseCost({...config,maxSteps:11}),/Step limit/);});
test('a model call requires current specific data consent and an admitted durable reservation',async()=>{const f=fixture();await assert.rejects(run(f)({...f.request,consent:{...f.request.consent,summaryDigest:'d'.repeat(64)}}),/Review/);assert.equal(f.calls.length,0);const denied=fixture('denied');await assert.rejects(run(denied)(denied.request),/No model request/);assert.deepEqual(denied.calls.map(c=>c[0]),['reserve']);const ok=fixture();assert.equal((await run(ok)(ok.request)).status,'complete');assert.deepEqual(ok.calls.map(c=>c[0]),['reserve','generate','settle']);assert.equal(ok.calls[0][1].reservedMicroUsd,4200);assert.equal(ok.calls[1][1].maxOutputTokens,500);});
test('duplicate or uncertain requests cannot silently charge twice',async()=>{const duplicate=fixture('duplicate');assert.equal((await run(duplicate)(duplicate.request)).status,'review');assert.deepEqual(duplicate.calls.map(c=>c[0]),['reserve']);const failed=fixture();failed.generate=async()=>{throw new Error('Synthetic provider failure with secret');};await assert.rejects(run(failed)(failed.request),/held for review/);assert.equal(failed.calls.at(-1)[1].status,'uncertain');assert.equal(failed.calls.at(-1)[1].chargedMicroUsd,null);});
test('unconfirmed billing retains its hold, and excess billing requires review',async()=>{const f=fixture();f.generate=async()=>({result:'Synthetic'});await assert.rejects(run(f)(f.request),/complete charge/);assert.equal(f.calls.at(-1)[1].status,'uncertain');const over=fixture();over.generate=async()=>({result:'Synthetic',chargedMicroUsd:4201});await assert.rejects(run(over)(over.request),/exceeded/);assert.equal(over.calls.at(-1)[1].status,'overrun');assert.equal(over.calls.at(-1)[1].chargedMicroUsd,4201);});
test('an unsupported coding subscription cannot be configured as finance API access',()=>{const f=fixture();assert.throws(()=>budgetedAdvisor({ledger:f.ledger,generate:f.generate,configuration:{...config,supportedFinanceTraffic:false},configurationHash:hash}),/supported finance API/);});
test('changed financial payloads and expired provider quotes cannot reach the budget or provider',async()=>{const f=fixture();await assert.rejects(run(f)({...f.request,summary:{currency:'CNY',privateNote:'Unapproved'}}),/summary.*changed/);assert.equal(f.calls.length,0);const expired=budgetedAdvisor({ledger:f.ledger,generate:f.generate,configuration:config,configurationHash:hash,now:()=>Date.parse(config.priceCheckedAt)+86400001});await assert.rejects(expired(f.request),/Recheck provider prices/);assert.equal(f.calls.length,0);});

test('a complete answer remains readable while its entire unconfirmed cost is held',async()=>{const f=fixture();f.generate=async()=>({result:'Verified answer',chargedMicroUsd:null});const result=await run(f)(f.request);assert.equal(result.status,'complete');assert.equal(result.chargedMicroUsd,null);assert.equal(result.result,'Verified answer');assert.equal(f.calls.at(-1)[1].status,'uncertain');});
