import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
let PGlite;try{({PGlite}=await import('../private/pg-tests/node_modules/@electric-sql/pglite/dist/index.js'));}catch{}
test('isolated private AI conversations keep admitted questions and immutable paginated history',{skip:!PGlite},async t=>{
 const db=new PGlite(),alice='11111111-1111-4111-8111-111111111111',bob='22222222-2222-4222-8222-222222222222',hash='a'.repeat(64),question='Synthetic question 中文 العربية';
 try{
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values('${alice}'),('${bob}');create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;grant usage on schema auth to authenticated,anon,service_role;grant execute on function auth.uid(),auth.jwt() to authenticated,anon;`);
  for(const file of ['schema-draft.sql','ai-budget-draft.sql','ai-conversations-draft.sql'])await db.exec(await readFile(new URL('../database/'+file,import.meta.url),'utf8'));
  const role=async(name='service_role',owner=alice,anonymous=false)=>{await db.exec('reset role;set role '+name);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:owner,is_anonymous:anonymous})]);};
  await role();await db.query("insert into plan_private.workspaces(owner_id,id,version) values($1,'w',1),($2,'w',1)",[alice,bob]);await db.query("insert into plan_private.ai_budgets(owner_id,period,limit_micro) values($1,to_char(now() at time zone 'UTC','YYYY-MM'),1000),($2,to_char(now() at time zone 'UTC','YYYY-MM'),1000)",[alice,bob]);
  const reserve=async(id,owner=alice)=>(await db.query('select public.plan_ai_reserve($1,$2,1,$3,$3,$3,$4) as result',[owner,id,hash,createHash('sha256').update(question).digest('hex')])).rows[0].result;
  const save=async(id,answer='Synthetic answer',owner=alice,text=question)=>(await db.query("select public.plan_ai_save_conversation($1,$2,'w',$3,$4) as result",[owner,id,text,answer])).rows[0].result;
  const history=async(owner=alice,before=null,limit=20)=>(await db.query("select public.plan_ai_read_conversations($1,'w',$2,$3) as result",[owner,before,limit])).rows[0].result;
  const id=crypto.randomUUID();
  await t.test('only admitted exact questions can be stored and retries cannot rewrite answers',async()=>{await assert.rejects(save(id),/admitted request/);assert.equal((await reserve(id)).status,'reserved');await assert.rejects(save(id,'Answer',alice,'Different question'),/admitted request/);assert.equal((await save(id)).status,'saved');assert.equal((await save(id)).status,'duplicate');await assert.rejects(save(id,'Rewritten answer'),/immutable/);assert.equal((await history()).messages[0].question,question);});
  await t.test('request and workspace ownership cannot be borrowed from another user',async()=>{await assert.rejects(save(id,'Synthetic answer',bob),/admitted request/);assert.equal((await history(bob)).messages.length,0);assert.equal((await history(bob,id)).messages.length,0);});
  await t.test('history pages keep stable identity even for equal timestamps and enforce bounded limits',async()=>{const ids=[];for(let i=0;i<3;i++){const next=crypto.randomUUID();ids.push(next);await reserve(next);}await db.query("select public.plan_ai_save_conversation($1,id,'w',$3,'Answer '||id::text) from unnest($2::uuid[]) as id",[alice,'{'+ids.join(',')+'}',question]);assert.equal((await db.query('select max(count) as ties from (select count(*) as count from plan_private.ai_conversations group by created_at) as grouped')).rows[0].ties,3);const first=await history(alice,null,2),second=await history(alice,first.nextCursor,2);assert.equal(first.messages.length,2);assert.equal(second.messages.length,2);assert.equal(second.nextCursor,null);assert.equal(new Set([...first.messages,...second.messages].map(m=>m.requestId)).size,4);await assert.rejects(history(alice,null,51),/Invalid history page/);});
  await t.test('anonymous and other users cannot read or write private conversations',async()=>{await role('authenticated',alice);assert.equal((await db.query('select * from plan_private.ai_conversations')).rows.length,4);await assert.rejects(save(crypto.randomUUID()),/permission denied/);await assert.rejects(db.exec("update plan_private.ai_conversations set answer='Changed'"),/permission denied/);await role('authenticated',bob);assert.equal((await db.query('select * from plan_private.ai_conversations')).rows.length,0);await role('authenticated',alice,true);assert.equal((await db.query('select * from plan_private.ai_conversations')).rows.length,0);await role('anon');await assert.rejects(db.exec('select * from plan_private.ai_conversations'),/permission denied/);await role();await assert.rejects(db.exec("update plan_private.ai_conversations set answer='Changed'"),/permission denied/);});
 }finally{await db.close();}
});
