import {test} from 'node:test';
import assert from 'node:assert/strict';
import {indexedDB} from 'fake-indexeddb';
import * as C from '../app/core.mjs';
import {prepareBackupReview,reviewCandidate,verifyBackupReview} from '../app/backup.mjs';
import {openStore,saveStore,loadStore,restoreReviewedBackup,syncRecovery} from '../app/storage.mjs';
globalThis.indexedDB=indexedDB;
async function exported(state){return JSON.stringify({app:'plan',schema:2,digest:await C.digest(JSON.stringify(state)),data:state});}
test('backup review verifies full digests and retains complete records without modifying either version',async()=>{const current=C.fresh(),candidate=C.mutate(current,'note-add',{},s=>s.notes.push({id:'n',title:'Synthetic',body:'中文 العربية',items:[]})),before=JSON.stringify({current,candidate}),review=await prepareBackupReview(current,await exported(candidate));assert.equal(review.kind,'full-backup');assert.deepEqual(await verifyBackupReview(current,review,review.digest),candidate);assert.equal(JSON.stringify({current,candidate}),before);await assert.rejects(prepareBackupReview(current,JSON.stringify({app:'plan',schema:2,digest:'wrong',data:candidate})),/integrity/);});
test('changed current records, candidate, review and unbounded input are rejected before restore',async()=>{const current=C.fresh(),review=await reviewCandidate(current,current),changed=C.mutate(current,'note-add',{},s=>s.notes.push({id:'n',title:'New',items:[]}));await assert.rejects(verifyBackupReview(changed,review,review.digest),/changed after preview/);await assert.rejects(verifyBackupReview(current,{...review,candidate:changed},review.digest),/review changed/);await assert.rejects(verifyBackupReview(current,{...review,kind:'original-backup'},review.digest),/review changed/);await assert.rejects(prepareBackupReview(current,'x'.repeat(10_000_001)),/10 MB/);await assert.rejects(prepareBackupReview(current,'{bad'),/valid JSON/);});
test('reviewed local restore requires confirmation and keeps the entire preceding version permanently',async()=>{const db=await openStore(),row=await loadStore(db),state=C.mutate(C.fresh(),'note-add',{},s=>s.notes.push({id:'kept',title:'Keep this earlier version',items:[]}));let revision=await saveStore(db,state,row.revision),candidate=C.fresh(),review=await reviewCandidate(state,candidate);await assert.rejects(restoreReviewedBackup(db,review,{expectedRevision:revision,reviewDigest:review.digest}),/confirm/);const restored=await restoreReviewedBackup(db,review,{expectedRevision:revision,reviewDigest:review.digest,confirmed:true});assert.deepEqual(restored.state,candidate);const recovery=await syncRecovery(db);assert.deepEqual(recovery.restores.at(-1).state,state);assert.ok(recovery.hold);assert.equal(restored.revision,revision+1);db.close();});
test('a concurrent local edit invalidates the reviewed replacement without archiving or erasing it',async()=>{const db=await openStore(),row=await loadStore(db),review=await reviewCandidate(row.state,C.fresh()),changed=C.mutate(row.state,'note-add',{},s=>s.notes.push({id:'concurrent',title:'Keep newer edit',items:[]}));const before=(await syncRecovery(db)).restores.length;await saveStore(db,changed,row.revision);await assert.rejects(restoreReviewedBackup(db,review,{expectedRevision:row.revision,reviewDigest:review.digest,confirmed:true}),/newer records/);assert.deepEqual((await loadStore(db)).state,changed);assert.equal((await syncRecovery(db)).restores.length,before);db.close();});
