import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
const date=C.today('Asia/Shanghai');
function fixture(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:s.currency,opening:10000,baselineDate:date,baselineSeq:0},{id:'wallet',name:'Wallet',kind:'asset',currency:s.currency,opening:0,baselineDate:date,baselineSeq:0},{id:'card',name:'Card',kind:'liability',currency:s.currency,opening:-10000,baselineDate:date,baselineSeq:0}];s.categories=[{id:'food',name:'Food',type:'variable'},{id:'oneoff',name:'Other',type:'variable'},{id:'savings',name:'Saving',type:'savings'}];const key=C.workspacePeriod(s,date);s.budgets=[{id:key,key,salary:20000,alloc:{food:5000,savings:4000},locks:{}}];return s;}
const tx=(s,kind,amount,extra={})=>C.addTransaction(s,{kind,amount,account:'bank',date,category:'',...extra});
test('budget reporting excludes transfers, borrowing and debt payments from earned income or spending',()=>{let s=fixture();s=tx(s,'income',3000);s=tx(s,'transfer',1000,{toAccount:'wallet'});s=tx(s,'repayment',2000,{toAccount:'card'});s=tx(s,'borrow',1000,{account:'card',toAccount:'bank'});const before=C.clone(s),r=C.budgetReport(s);assert.equal(r.actualIncome,3000);assert.equal(r.actualSpending,0);assert.equal(r.expectedIncome,20000);assert.deepEqual(s,before);});
test('split expenses and refunds count exact category amounts while reversals retain history',()=>{let s=fixture();s=tx(s,'expense',1000,{category:'food',splits:[{category:'food',amount:600},{category:'oneoff',amount:400}]});s=tx(s,'refund',100,{category:'food'});let r=C.budgetReport(s);assert.equal(r.actualSpending,900);assert.equal(r.categories.find(c=>c.id==='food').actual,500);s=C.reverseTransaction(s,s.transactions[0].id,'Wrong purchase');r=C.budgetReport(s);assert.equal(r.actualSpending,-100);assert.equal(r.categories.find(c=>c.id==='food').actual,-100);assert.equal(s.transactions.length,3);});
test('archived category allocations remain visible and overspending stays signed',()=>{let s=fixture();s=tx(s,'expense',6000,{category:'food'});s.categories[0].archived=true;const r=C.budgetReport(s),food=r.categories.find(c=>c.id==='food');assert.equal(food.archived,true);assert.equal(food.budget,5000);assert.equal(food.remaining,-1000);assert.equal(r.categories.find(c=>c.id==='savings').actual,0);});
test('an imported historical month is not remapped by its timestamp or the current cycle',()=>{const s=fixture();s.transactions=[{id:'legacy',seq:0,kind:'expense',date,amount:123,account:'',category:'food',postings:[],historical:true,source:'legacy',legacyPeriod:'2020-01'}];assert.equal(C.budgetReport(s,'2020-01').actualSpending,123);assert.equal(C.budgetReport(s).actualSpending,0);});
test('carried budgets are assumptions and absent categories remain uncategorized',()=>{let s=fixture();s=tx(s,'expense',100);s.categories=s.categories.filter(c=>c.id!=='oneoff');const r=C.budgetReport(s);assert.equal(r.categories.find(c=>c.id==='oneoff').actual,100);assert.equal(C.budgetReport(s,C.addMonths(C.workspacePeriod(s,date),1)).exactBudget,false);});

test('budget updates retain archived allocations, locks and original identity unless explicitly revised',()=>{const s=fixture(),key=C.workspacePeriod(s,date);s.budgets[0].id='original-budget';s.budgets[0].locks={food:true};s.categories[0].archived=true;const after=C.setBudget(s,{key,salary:10000,alloc:{savings:1000}});assert.equal(after.budgets[0].id,'original-budget');assert.equal(after.budgets[0].alloc.food,5000);assert.equal(after.budgets[0].locks.food,true);assert.equal(C.setBudget(after,{key,salary:10000,alloc:{food:0}}).budgets[0].alloc.food,0);assert.throws(()=>C.setBudget(s,{key:C.addMonths(key,-1),salary:1,alloc:{food:0}}),/Historical/);});
