import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
import {diffEntities} from '../app/sync.mjs';
import {validateOperation} from '../server/validation.mjs';
const asOf='2026-10-07';
function fixture(){const s=C.fresh();s.categories=[{id:'food',name:'Food',type:'variable',archived:false},{id:'oneoff',name:'Uncategorized',type:'variable'},{id:'saving-intent',name:'Saving',type:'savings'}];s.accounts=[{id:'cash',name:'Cash',kind:'asset',currency:s.currency,opening:10000,baselineDate:'2026-10-01',baselineSeq:0,verified:true}];s.budgets=[{id:'original',key:C.workspacePeriod(s,asOf),salary:20000,alloc:{food:5000,'saving-intent':1000},locks:{food:true}}];return C.addTransaction(s,{kind:'expense',amount:1000,account:'cash',category:'food',date:asOf});}
const check=(before,after,type)=>validateOperation(before,{workspace:before.id,operationId:crypto.randomUUID(),expectedVersion:before.version,type,patches:diffEntities(before,after)},{asOf});
test('category archive and restore retain allocations, spending evidence and verified cash',()=>{const before=fixture(),archived=C.toggleCategoryArchive(before,'food');assert.deepEqual(archived.budgets,before.budgets);assert.deepEqual(archived.transactions,before.transactions);assert.equal(C.summary(archived).cash,C.summary(before).cash);const row=C.budgetReport(archived,C.workspacePeriod(before,asOf)).categories.find(c=>c.id==='food');assert.equal(row.budget,5000);assert.equal(row.actual,1000);assert.equal(row.archived,true);assert.equal(check(before,archived,'category-archive').categories[0].archived,true);assert.equal(check(archived,C.toggleCategoryArchive(archived,'food'),'category-archive').categories[0].archived,false);});
test('category creation validates names and ordinary types while preserving built-in intentions',()=>{const before=fixture(),added=C.addCategory(before,{name:'  中文 العربية  ',type:'fixed'});assert.equal(added.categories.at(-1).name,'中文 العربية');assert.equal(check(before,added,'category-add').categories.at(-1).type,'fixed');for(const name of ['', '  ','x'.repeat(301)])assert.throws(()=>C.addCategory(before,{name}),/category name/);assert.throws(()=>C.addCategory(before,{name:'New',type:'savings'}),/spending category/);for(const id of ['oneoff','saving-intent','missing'])assert.throws(()=>C.toggleCategoryArchive(before,id),/available/);});
test('cloud category commands cannot rewrite old names, allocations or category meaning',()=>{const before=fixture(),added=C.addCategory(before,{name:'Transport'}),renamed=C.clone(added);renamed.categories[0].name='Rewritten history';assert.throws(()=>check(before,renamed,'category-add'),/authoritative operation/);const archived=C.toggleCategoryArchive(before,'food'),forged=C.clone(archived);forged.categories[0].type='fixed';assert.throws(()=>check(before,forged,'category-archive'),/authoritative operation/);const changed=C.clone(archived);changed.budgets[0].alloc.food=0;assert.throws(()=>check(before,changed,'category-archive'),/cannot change/);});
