import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
import * as S from '../app/sync.mjs';
import {privateCloudTransport} from '../frontend/cloud-transport.mjs';
import {createSyncHttpHandler} from '../server/sync-http.mjs';
const origin='https://plan.example.test',owner='11111111-1111-4111-8111-111111111111';

test('stalled or rejected sign-in is bounded and late credentials cannot start a request',async()=>{
  let release,calls=0;const credentials=new Promise(resolve=>release=resolve),config={origin,currentOrigin:origin,timeoutMs:20,fetchImpl:async()=>{calls++;return Response.json({});}};
  const delayed=privateCloudTransport({...config,tokenProvider:()=>credentials});await assert.rejects(delayed.read('w'),/Sign-in could not be confirmed/);release('valid');await new Promise(resolve=>setTimeout(resolve,10));assert.equal(calls,0);
  const rejected=privateCloudTransport({...config,tokenProvider:async()=>{throw new Error('private-session-token');}});await assert.rejects(rejected.read('w'),e=>e.message.includes('Sign-in could not be confirmed')&&!e.message.includes('private-session-token'));assert.equal(calls,0);
});
function setup(){const state=C.fresh();state.version=1;const after=C.mutate(state,'note-add',{},n=>n.notes.push({id:'n',title:'Synthetic',body:'',items:[]})),operation={workspace:state.id,operationId:crypto.randomUUID(),expectedVersion:1,type:'note-add',patches:S.diffEntities(state,after)},calls=[];const snapshot={workspace:state.id,version:1,records:S.entities(state).map(r=>({...r,version:1})),operations:[]};const handler=createSyncHttpHandler({origin,admit:async()=>({allowed:true}),verifySession:async token=>token==='valid'?{id:owner,is_anonymous:false}:null,store:{read:async()=>C.clone(snapshot),apply:async()=>({status:'applied',version:2})}});const fetchImpl=async(url,options)=>{calls.push({url,options});return handler(new Request(url,{...options,headers:{...options.headers,origin,'sec-fetch-site':'same-origin'}}));};const config={origin,currentOrigin:origin,tokenProvider:async()=>'valid',fetchImpl};return {state,operation,snapshot,calls,config,transport:privateCloudTransport(config)};}
test('prepared transport is inert until called and integrates verified snapshots, writes and conflicts',async()=>{const f=setup();assert.equal(f.calls.length,0);assert.deepEqual(await f.transport.read(f.state.id),f.snapshot);assert.deepEqual(await f.transport.apply(f.operation),{status:'applied',version:2});assert.deepEqual(await f.transport.apply({...f.operation,expectedVersion:0}),{status:'conflict',version:1});assert.equal(f.calls.length,3);assert.equal(f.calls[0].options.credentials,'same-origin');assert.equal(f.calls[0].options.redirect,'error');assert.equal(f.calls[0].options.cache,'no-store');assert.equal(f.calls[1].options.body.includes('"owner"'),false);});
test('transport cannot send tokens to another origin or send owner injection/unreviewed bootstrap',async()=>{const f=setup();assert.throws(()=>privateCloudTransport({...f.config,currentOrigin:'https://different.test'}),/current HTTPS/);assert.throws(()=>f.transport.apply({...f.operation,owner:'attacker'}),/owner field/);assert.throws(()=>f.transport.bootstrap({workspace:f.state.id,review:{confirmed:false}}),/Review/);const anonymous=privateCloudTransport({...f.config,tokenProvider:async()=>null});await assert.rejects(anonymous.read(f.state.id),/Sign in/);assert.equal(f.calls.length,0);});
test('wrong-workspace reads, impossible acknowledgments and raw server errors never reach local acknowledgment',async()=>{const f=setup();for(const result of [{...f.snapshot,workspace:'other'},{...f.snapshot,records:[]}]){const transport=privateCloudTransport({...f.config,fetchImpl:async()=>Response.json({action:'read',result})});await assert.rejects(transport.read(f.state.id),/did not confirm/);}for(const response of [Response.json({action:'apply',result:{status:'applied',version:100}}),Response.json({action:'apply',result:{status:'conflict',version:1}}),new Response('secret-token private-finances',{status:500})]){const transport=privateCloudTransport({...f.config,fetchImpl:async()=>response});await assert.rejects(transport.apply(f.operation),e=>e.message.includes('did not confirm')&&!e.message.includes('secret-token'));}});
test('uncertain writes and oversized/slow responses retain caller input and never retry',async()=>{const f=setup(),before=JSON.stringify(f.operation);let calls=0;const failed=privateCloudTransport({...f.config,fetchImpl:async()=>{calls++;throw new Error('private upstream token');}});await assert.rejects(failed.apply(f.operation),/Keep local edits/);assert.equal(calls,1);assert.equal(JSON.stringify(f.operation),before);const huge=privateCloudTransport({...f.config,fetchImpl:async()=>new Response('x'.repeat(4_000_001),{headers:{'content-type':'application/json'}})});await assert.rejects(huge.read(f.state.id),/did not confirm/);let cancelled=false;const slow=privateCloudTransport({...f.config,timeoutMs:20,fetchImpl:async()=>new Response(new ReadableStream({cancel(){cancelled=true;}}),{headers:{'content-type':'application/json'}})});await assert.rejects(slow.read(f.state.id),/did not confirm/);assert.equal(cancelled,true);});
test('an operation is captured before credentials resolve and duplicate acknowledgments must confirm a newer version',async()=>{const f=setup();let release;const token=new Promise(resolve=>release=resolve),transport=privateCloudTransport({...f.config,tokenProvider:()=>token}),pending=transport.apply(f.operation);f.operation.expectedVersion=900;release('valid');assert.deepEqual(await pending,{status:'applied',version:2});assert.equal(JSON.parse(f.calls[0].options.body).request.expectedVersion,1);const falseDuplicate=privateCloudTransport({...f.config,fetchImpl:async()=>Response.json({action:'apply',result:{status:'duplicate',version:1}})});await assert.rejects(falseDuplicate.apply({...f.operation,expectedVersion:1}),/did not confirm/);});

test('a response arriving after timeout is cancelled without reading or acknowledging local edits',async()=>{
 const f=setup();let release,calls=0,cancelled=0;
 const transport=privateCloudTransport({...f.config,timeoutMs:5,fetchImpl:async()=>{calls++;return new Promise(resolve=>{release=resolve;});}});
 await assert.rejects(transport.apply(f.operation),/Keep local edits/);
 release(new Response(new ReadableStream({cancel(){cancelled++;}}),{headers:{'content-type':'application/json'}}));await new Promise(resolve=>setTimeout(resolve,0));
 assert.equal(cancelled,1);assert.equal(calls,1);assert.equal(f.operation.expectedVersion,1);
});
