import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
function example(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:s.currency,opening:100000,baselineDate:'2026-10-01',baselineSeq:0,verified:true}];s.categories=[{id:'food',name:'Food',type:'variable'}];return C.addTransaction(s,{kind:'expense',date:'2026-10-06',amount:1000,account:'bank',category:'food',note:'Original 中文'});}
const replacement={kind:'expense',date:'2026-10-06',amount:1500,account:'bank',category:'food',note:'Corrected العربية'};
test('a reviewed replacement is one operation and preserves original ledger and exact net amounts',()=>{const s=example(),original=C.clone(s.transactions[0]),next=C.correctTransaction(s,{id:original.id,replacement,reason:'Statement amount was different'});assert.deepEqual(next.transactions[0],original);assert.equal(next.transactions.length,3);assert.equal(next.operations.length,s.operations.length+1);assert.equal(next.seq,s.seq+1);assert.equal(next.transactions[1].seq,next.transactions[2].seq);assert.equal(next.transactions[1].reverses,original.id);assert.equal(next.transactions[2].corrects,original.id);assert.equal(C.accountBalance(next,'bank','2026-10-07'),98500);assert.equal(C.expenseTotal(next,'2026-09'),1500);assert.equal(C.canCorrectTransaction(next,original.id),false);assert.equal(next.operations.at(-1).patches.filter(p=>p.collection==='transactions').length,2);});
test('an invalid replacement neither leaves a reversal nor modifies the original state',()=>{const s=example(),before=C.clone(s);assert.throws(()=>C.correctTransaction(s,{id:s.transactions[0].id,replacement:{...replacement,amount:0},reason:'Test'}),/above zero/);assert.throws(()=>C.correctTransaction(s,{id:s.transactions[0].id,replacement,reason:' '}),/Explain/);assert.deepEqual(s,before);});
test('a correction before a later checked balance changes spending history without creating cash',()=>{let s=example();s=C.reconcile(s,{account:'bank',date:'2026-10-07',balance:99000});const next=C.correctTransaction(s,{id:s.transactions[0].id,replacement,reason:'Historical amount review'});assert.equal(C.accountBalance(next,'bank','2026-10-07'),99000);assert.equal(C.expenseTotal(next,'2026-09'),1500);});
test('linked scheduled or outside payments and transfer replacements require their own workflow',()=>{const s=example();s.obligations=[{id:'bill',kind:'bill',name:'Bill',date:'2026-10-06',amount:1000,account:'bank',paid:true,transaction:s.transactions[0].id}];assert.equal(C.canCorrectTransaction(s,s.transactions[0].id),false);assert.throws(()=>C.correctTransaction(s,{id:s.transactions[0].id,replacement,reason:'Test'}),/linked workflow/);const unlinked=example();assert.throws(()=>C.correctTransaction(unlinked,{id:unlinked.transactions[0].id,replacement:{...replacement,kind:'transfer'},reason:'Test'}),/ordinary correction/);});
