import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
function fixture(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:'CNY',opening:0,baselineDate:'2026-10-06',baselineSeq:0}];s.categories=[{id:'food',name:'Food',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:100000,alloc:{food:20000},locks:{}}];s.goals=[{id:'g',name:'Purchase',target:100000,priority:1}];s.reservations={g:0};return s;}
test('the goal path finds the minimum income increase to the exact minor unit',()=>{const s=fixture(),old=C.clone(s),r=C.goalIncomePath(s,{id:'g',deadline:'2026-11-14',asOf:'2026-10-06',periods:3});assert.equal(r.feasible,true);assert.equal(r.additionalIncome,20000);assert.equal(r.ready,'2026-11-14');const less=C.planGoals(s,{asOf:'2026-10-06',periods:3,incomeChange:r.additionalIncome-1});assert.notEqual(less.results[0].ready,'2026-11-14');assert.deepEqual(s,old);});
test('existing savings and continued protection change the needed future increase',()=>{const s=fixture();s.accounts[0].opening=20000;assert.equal(C.goalIncomePath(s,{id:'g',deadline:'2026-11-14',asOf:'2026-10-06',periods:3}).additionalIncome,0);s.accounts[0].opening=0;s.settings.monthlyProtection=10000;assert.equal(C.goalIncomePath(s,{id:'g',deadline:'2026-11-14',asOf:'2026-10-06',periods:3}).additionalIncome,30000);});
test('an earlier hard deadline keeps its share of the same money pool',()=>{const s=fixture();s.goals.push({id:'other',name:'Earlier bill purchase',target:50000,priority:2,flexible:false,desired:'2026-11-13'});s.reservations.other=0;const r=C.goalIncomePath(s,{id:'g',deadline:'2026-11-14',asOf:'2026-10-06',periods:3});assert.equal(r.additionalIncome,70000);assert.equal(r.plan.results.find(g=>g.id==='other').funded,50000);});
test('more future income cannot invent a funding date before the first eligible period',()=>{const r=C.goalIncomePath(fixture(),{id:'g',deadline:'2026-10-20',asOf:'2026-10-06',periods:3});assert.equal(r.feasible,false);assert.equal(r.additionalIncome,null);assert.ok(r.reason.includes('No future'));});
test('a missing transition budget blocks inverse forecasts too',()=>{const s=C.scheduleCycle(fixture(),{start:1,effective:'2026-10-15'},'2026-10-06');const r=C.goalIncomePath(s,{id:'g',deadline:'2026-12-01',asOf:'2026-10-06',periods:3});assert.equal(r.feasible,false);assert.ok(r.reason.includes('transition'));});
