import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
const asOf='2026-10-06';
function fixture(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:s.currency,opening:10000,baselineDate:asOf,baselineSeq:0}];s.categories=[{id:'food',name:'Food',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:100000,alloc:{food:0},locks:{}}];s.goals=[1,2,3].map(i=>({id:'g'+i,name:'Goal '+i,kind:'purchase',target:8000,priority:i}));s.obligations=[{id:'pay1',name:'Pay 1',kind:'income',amount:-10000,date:'2026-10-08',account:'bank',paid:false},{id:'pay2',name:'Pay 2',kind:'income',amount:-10000,date:'2026-10-15',account:'bank',paid:false}];return s;}
const plan=(s,extra={})=>C.planPurchaseDates(s,{account:'bank',asOf,days:16,...extra});
test('joint dated goals consume one cash pool rather than each claiming the same savings',()=>{const s=fixture(),before=C.clone(s),r=plan(s);assert.deepEqual(r.results.map(g=>g.date),[asOf,'2026-10-09','2026-10-16']);assert.equal(r.planned.reduce((n,p)=>n+p.amount,0),24000);assert.deepEqual(s,before);assert.equal(r.recordsChanged,false);});
test('budget salary alone never funds joint dated purchases',()=>{const s=fixture();s.obligations=[];assert.deepEqual(plan(s).results.map(g=>g.date),[asOf,null,null]);s.budgets[0].salary=999999;assert.deepEqual(plan(s).results.map(g=>g.date),[asOf,null,null]);});
test('each goal may consume its own reservation only at its purchase date',()=>{const s=fixture();s.accounts[0].opening=17000;s.reservations={g1:8000,g2:8000};s.obligations=[];const r=plan(s);assert.deepEqual(r.results.map(g=>g.date),[asOf,asOf,null]);assert.equal(r.preview.initialFloor,16000);assert.equal(s.reservations.g1,8000);});
test('higher-priority infeasible goals block later purchases and hard deadlines order the queue',()=>{const s=fixture();s.goals[0].target=100000;assert.ok(plan(s).results.every(g=>g.date===null));s.goals[1].desired='2026-10-10';s.goals[1].flexible=false;const r=plan(s);assert.equal(r.results[0].id,'g2');assert.equal(r.results[0].date,asOf);assert.equal(r.results[1].date,null);});
test('ongoing costs are reserved after proposed purchase completion',()=>{const s=fixture();s.goals=[s.goals[0]];s.goals[0].recurringCost=5000;s.obligations=[];assert.equal(plan(s,{days:40}).results[0].date,null);assert.ok(plan(s,{days:40}).preview.rows.some(row=>row.name.includes('proposed ongoing cost')));s.goals[0].recurringCost=1000;assert.equal(plan(s,{days:40}).results[0].date,asOf);});
test('missing budgets, unknown cash and short payment accounts prevent joint dates',()=>{const s=fixture();s.budgets=[];assert.ok(plan(s).results.every(g=>g.date===null));s.budgets=fixture().budgets;s.accounts[0].opening=null;assert.ok(plan(s).results.every(g=>g.date===null));const split=fixture();split.accounts.push({id:'wallet',name:'Wallet',kind:'asset',currency:split.currency,opening:100,baselineDate:asOf,baselineSeq:0});assert.ok(plan(split,{account:'wallet',budgetAccount:'bank'}).results.every(g=>g.date===null));});
test('a scenario cannot release the same goal reservation twice or use protected savings',()=>{const s=fixture();s.goals[0].protected=true;assert.ok(!plan(s).results.some(g=>g.id==='g1'));assert.throws(()=>C.purchaseSafety(s,{amount:100,account:'bank',date:asOf,asOf,days:16,goalId:'g2',plannedPurchases:[{goalId:'g2',amount:1,account:'bank',date:asOf}]}),/distinct active/);});
