import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
import {diffEntities} from '../app/sync.mjs';
import {validateOperation} from '../server/validation.mjs';
const asOf=C.today('Asia/Shanghai');
const check=(before,after,type)=>validateOperation(before,{workspace:before.id,operationId:crypto.randomUUID(),expectedVersion:before.version,type,patches:diffEntities(before,after)},{asOf});
function fixture(){const s=C.fresh();s.seq=1;s.categories=[{id:'oneoff',name:'One-off',type:'variable'}];s.accounts=[{id:'cash',name:'Cash',kind:'asset',currency:s.currency,opening:10000,baselineDate:asOf,baselineSeq:1,verified:true}];s.goals=[{id:'g',name:'Gold',target:2000,priority:1,kind:'gold',quantity:2,recurringCost:100,archived:false}];s.reservations.g=1000;return s;}
test('recording a scheduled payment advances the ledger and calendar in one queued operation',()=>{const before=fixture();before.obligations=[{id:'bill',name:'Bill',kind:'bill',date:asOf,amount:100,account:'cash',paid:false}];const after=C.recordScheduled(before,'bill',asOf);assert.equal(after.seq,before.seq+1);assert.equal(after.version,before.version+1);assert.equal(after.operations.length,before.operations.length+1);assert.equal(after.operations.at(-1).type,'obligation-paid');assert.equal(check(before,after,'obligation-paid').obligations[0].transaction,after.transactions[0].id);const forged=C.clone(after);forged.transactions[0].amount=101;forged.transactions[0].postings[0].amount=-101;assert.throws(()=>check(before,forged,'obligation-paid'),/authoritative/);});
test('cloud scheduled payments cannot rewrite the template or another occurrence',()=>{const before=fixture();before.obligations=[{id:'bill',name:'Bill',kind:'bill',date:asOf,amount:100,account:'cash',paid:false,recurrence:{unit:'weekly',interval:1}}];const after=C.recordScheduled(before,'bill');after.obligations[0].amount=200;assert.throws(()=>check(before,after,'obligation-paid'),/authoritative/);});
test('linked purchase and reversal preserve exact costs, holdings and ongoing bills',()=>{const before=fixture(),bought=C.purchaseGoal(before,{id:'g',amount:2000,account:'cash',date:asOf});assert.equal(check(before,bought,'goal-purchase').holdings[0].cost,2000);const reversed=C.reverseTransaction(bought,bought.transactions[0].id,'Correction');assert.equal(check(bought,reversed,'reverse').goals[0].archived,false);for(const change of [n=>n.holdings[0].cost=2001,n=>n.holdings[0].quantity=3,n=>n.obligations[0].amount=200,n=>n.reservations.g=1]){const forged=C.clone(bought);change(forged);assert.throws(()=>check(before,forged,'goal-purchase'),/authoritative|available cash/);}});
test('a reversal cannot leave purchased gold or recurring costs active',()=>{const bought=C.purchaseGoal(fixture(),{id:'g',amount:2000,account:'cash',date:asOf}),after=C.reverseTransaction(bought,bought.transactions[0].id,'Correction');const forged=C.clone(after);delete forged.holdings[0].reversedBy;assert.throws(()=>check(bought,forged,'reverse'),/authoritative/);const hidden=C.clone(after);hidden.obligations[0].archived=false;assert.throws(()=>check(bought,hidden,'reverse'),/authoritative/);});
test('a goal purchase cannot consume protected cash by supplying self-consistent ledger patches',()=>{const before=fixture();before.settings.reserve=8000;const bought=C.purchaseGoal(before,{id:'g',amount:2000,account:'cash',date:asOf}),forged=C.clone(bought);forged.transactions[0].amount=3001;forged.transactions[0].postings[0].amount=-3001;forged.goals[0].purchase.amount=3001;forged.goals[0].purchases[0].amount=3001;forged.holdings[0].cost=3001;assert.throws(()=>check(before,forged,'goal-purchase'),/protected cash/);});
test('outside returns and their reversals preserve the original amount and exact outstanding balance',()=>{const before=C.giveOutside(fixture(),{name:'Loan',kind:'loan',amount:1000,account:'cash',date:asOf}),after=C.returnOutside(before,{id:before.outside[0].id,amount:200,account:'cash',date:asOf});assert.equal(check(before,after,'outside-return').outside[0].returned,200);const reversed=C.reverseTransaction(after,after.transactions.at(-1).id,'Wrong receipt');assert.equal(check(after,reversed,'reverse').outside[0].returned,0);const forged=C.clone(after);forged.outside[0].name='Rewritten purpose';assert.throws(()=>check(before,forged,'outside-return'),/authoritative/);});
test('cancelled overdue bills leave the weekly review without recording an actual payment',()=>{const s=fixture(),date=new Date(asOf+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-1);s.obligations=[{id:'old',name:'No longer due',kind:'bill',date:date.toISOString().slice(0,10),amount:100,account:'cash',paid:false}];assert.ok(C.weeklyReview(s,{asOf}).items.some(i=>i.kind==='overdue'));const after=C.cancelScheduledOccurrence(s,{id:'old',reason:'Not due'});assert.ok(!C.weeklyReview(after,{asOf}).items.some(i=>i.kind==='overdue'));assert.equal(after.transactions.length,0);});
