import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
function fixture(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:'CNY',opening:100000,baselineDate:'2026-10-06',baselineSeq:0}];s.categories=[{id:'food',name:'Food',type:'variable'},{id:'oneoff',name:'Other',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:200000,alloc:{food:30000},locks:{}}];return s;}
const preview=(s,options={})=>C.purchaseSafety(s,{amount:80000,account:'bank',date:'2026-10-06',asOf:'2026-10-06',days:7,...options});
test('purchase timing reserves unspent normal spending instead of promising all cash',()=>{const s=fixture(),before=C.clone(s),r=preview(s);assert.equal(r.safe,false);assert.equal(r.minimum,-10000);assert.deepEqual(s,before);assert.equal(preview(s,{amount:60000}).safe,true);});
test('recorded normal expenses are not deducted twice from the remaining allowance',()=>{let s=fixture();s=C.addTransaction(s,{kind:'expense',amount:10000,account:'bank',date:'2026-10-06',category:'food'});const r=preview(s,{amount:60000});assert.equal(r.minimum,10000);assert.equal(r.safe,true);});
test('salary budget alone cannot fund a purchase before an actual dated receipt',()=>{const s=fixture();assert.equal(preview(s,{amount:120000}).safe,false);s.obligations=[{id:'salary',name:'Salary',kind:'income',amount:-100000,date:'2026-10-08',account:'bank',paid:false}];assert.equal(preview(s,{amount:120000}).safe,false);const later=preview(s,{amount:120000,date:'2026-10-09'});assert.equal(later.safe,true);assert.equal(later.conditional,true);});
test('a generic purchase preview cannot consume goal reservations or protected money',()=>{const s=fixture();s.goals=[{id:'g',name:'Another goal',target:20000,priority:1}];s.reservations={g:20000};s.settings.reserve=10000;assert.equal(preview(s,{amount:50000}).safe,false);assert.equal(preview(s,{amount:40000}).safe,true);});
test('missing budgets or account baselines prevent a reassuring purchase verdict',()=>{const s=fixture();s.budgets=[];assert.equal(preview(s,{amount:1000}).safe,false);assert.equal(preview(s).missingBudget,true);s.accounts[0].opening=null;assert.equal(preview(s).known,false);});
test('same-day bills are tested before income, and the chosen account must stay solvent',()=>{const s=fixture();s.accounts.push({id:'wallet',name:'Wallet',kind:'asset',currency:'CNY',opening:1000,baselineDate:'2026-10-06',baselineSeq:0});const r=preview(s,{amount:2000,account:'wallet',budgetAccount:'bank'});assert.equal(r.safe,false);assert.ok(r.accountShort.length);s.obligations=[{id:'bill',name:'Rent',kind:'bill',amount:80000,date:'2026-10-08',account:'bank',paid:false},{id:'salary',name:'Salary',kind:'income',amount:-100000,date:'2026-10-08',account:'bank',paid:false}];assert.equal(preview(s,{amount:1000,date:'2026-10-09'}).safe,false);});
