import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
function fixture(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:s.currency,opening:10000,baselineDate:'2026-10-06',baselineSeq:0}];s.categories=[{id:'food',name:'Food',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:20000,alloc:{food:3000},locks:{}}];return s;}
const window=(s,options={})=>C.purchaseWindow(s,{amount:12000,account:'bank',asOf:'2026-10-06',days:7,...options});
test('a conditional purchase date follows the actual dated receipt rather than budget salary',()=>{const s=fixture(),before=C.clone(s);assert.equal(window(s).earliest,null);s.obligations=[{id:'pay',name:'Pay',kind:'income',amount:-10000,date:'2026-10-08',account:'bank',paid:false}];const result=window(s);assert.equal(result.earliest,'2026-10-09');assert.equal(result.preview.safe,true);assert.equal(result.preview.conditional,true);assert.deepEqual(before.accounts,s.accounts);assert.equal(s.transactions.length,0);});
test('a goal purchase can use only its own reservation at payment time',()=>{const s=fixture();s.goals=[{id:'g',name:'Purchase',kind:'purchase',target:6000,priority:1},{id:'other',name:'Other',kind:'purchase',target:2000,priority:2}];s.reservations={g:6000,other:2000};s.budgets[0].alloc.food=1000;assert.equal(window(s,{amount:6000}).earliest,null);const result=window(s,{amount:6000,goalId:'g'});assert.equal(result.earliest,'2026-10-06');assert.equal(result.preview.initialFloor,8000);assert.equal(result.preview.floor,2000);assert.equal(result.preview.reservationUsed,6000);assert.equal(s.reservations.g,6000);assert.equal(window(s,{amount:9000,goalId:'g'}).earliest,null);});
test('a future goal purchase cannot release reservations early to hide a bill shortfall',()=>{const s=fixture();s.goals=[{id:'g',name:'Purchase',kind:'purchase',target:8000,priority:1}];s.reservations.g=8000;s.budgets[0].alloc.food=0;s.obligations=[{id:'bill',name:'Bill',kind:'bill',amount:3000,date:'2026-10-07',account:'bank',paid:false},{id:'pay',name:'Pay',kind:'income',amount:-20000,date:'2026-10-08',account:'bank',paid:false}];const r=C.purchaseSafety(s,{amount:8000,goalId:'g',account:'bank',date:'2026-10-09',asOf:'2026-10-06',days:7});assert.equal(r.safe,false);assert.ok(r.breaches.some(row=>row.date==='2026-10-07'));});
test('missing evidence or a short purchase account prevents an automatic date',()=>{const s=fixture();s.budgets=[];assert.equal(window(s,{amount:1}).earliest,null);s.budgets=fixture().budgets;s.accounts.push({id:'wallet',name:'Wallet',kind:'asset',currency:s.currency,opening:100,baselineDate:'2026-10-06',baselineSeq:0});s.obligations=[{id:'pay',name:'Pay',kind:'income',amount:-100000,date:'2026-10-08',account:'bank',paid:false}];assert.equal(window(s,{amount:200,account:'wallet',budgetAccount:'bank'}).earliest,null);});
