import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
function fixture(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:s.currency,opening:10000,baselineDate:'2026-10-06',baselineSeq:0}];s.categories=[{id:'food',name:'Food',type:'variable'},{id:'oneoff',name:'Other',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:20000,alloc:{food:3000},locks:{}}];s.obligations=[{id:'bill',name:'Bill',kind:'bill',amount:3000,date:'2026-10-07',account:'bank',paid:false}];return s;}
test('unlinked bills reduce forecast capacity, while a mapped bill uses its category budget once',()=>{const s=fixture();assert.equal(C.periodForecast(s,'2026-09').capacity,14000);s.obligations[0].budgetCategory='food';assert.equal(C.periodForecast(s,'2026-09').capacity,17000);s.obligations[0].amount=4000;assert.equal(C.periodForecast(s,'2026-09').capacity,16000);});
test('purchase timing places a mapped bill on its due date instead of reserving it twice',()=>{const s=fixture(),preview=()=>C.purchaseSafety(s,{amount:6000,account:'bank',date:'2026-10-08',asOf:'2026-10-06',days:7});assert.equal(preview().safe,false);s.obligations[0].budgetCategory='food';const r=preview();assert.equal(r.safe,true);assert.equal(r.minimum,1000);assert.equal(r.rows.filter(row=>row.amount===-3000).length,1);});
test('recording a mapped bill keeps its category and does not count a paid bill twice',()=>{const s=fixture();s.obligations[0].budgetCategory='food';const paid=C.recordScheduled(s,'bill','2026-10-07');assert.equal(paid.transactions[0].category,'food');assert.equal(C.periodForecast(paid,'2026-09').capacity,17000);assert.equal(C.accountBalance(paid,'bank','2026-10-07'),7000);});
test('remaining mapped commitments add to recorded category spending before applying its allowance',()=>{let s=fixture();s.obligations[0].budgetCategory='food';s=C.addTransaction(s,{kind:'expense',amount:2000,category:'food',account:'bank',date:'2026-10-06'});assert.equal(C.periodForecast(s,'2026-09').capacity,15000);});
test('a debt payment or expected income cannot be hidden inside a spending budget category',()=>{const s=fixture();s.obligations[0].budgetCategory='food';s.accounts.push({id:'debt',name:'Debt',kind:'liability',currency:s.currency,opening:-10000,baselineDate:'2026-10-06',baselineSeq:0});s.obligations[0].debtAccount='debt';assert.throws(()=>C.validateState(s),/ordinary bill/);delete s.obligations[0].debtAccount;s.obligations[0].kind='income';s.obligations[0].amount=-3000;assert.throws(()=>C.validateState(s),/ordinary bill/);});
test('a reversed expense is removed from historical capacity assumptions',()=>{let s=fixture();s.obligations=[];s.budgets[0].alloc.food=0;s=C.addTransaction(s,{kind:'expense',amount:15000,category:'food',account:'bank',date:'2026-08-20'});assert.equal(C.periodForecast(s,'2026-09',{mode:'history'}).spending,15000);s=C.reverseTransaction(s,s.transactions[0].id);assert.equal(C.periodForecast(s,'2026-09',{mode:'history'}).spending,0);});
