import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
import {diffEntities} from '../app/sync.mjs';
import {validateOperation} from '../server/validation.mjs';
const checked=(before,after,type)=>validateOperation(before,{workspace:before.id,operationId:crypto.randomUUID(),expectedVersion:before.version,type,patches:diffEntities(before,after)},{asOf:'2026-10-07'});
function fixture(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:s.currency,opening:10000,baselineDate:'2026-10-01',baselineSeq:0}];s.categories=[{id:'oneoff',name:'Other',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:20000,alloc:{},locks:{}}];s.obligations=[{id:'bill',name:'Weekly bill',kind:'bill',amount:1000,date:'2026-10-01',account:'bank',paid:false,recurrence:{unit:'weekly',interval:1}}];return s;}
test('cancelling one occurrence keeps future repeats and removes only its cash projection',()=>{const before=fixture(),next=C.cancelScheduledOccurrence(before,{id:'bill',reason:'Waived first bill'}),events=C.scheduledEvents(next,{from:'2026-10-01',to:'2026-10-15'});assert.equal(events[0].skipped,true);assert.equal(events[1].skipped,false);assert.equal(events.length,3);assert.equal(C.cashCalendar(next,{asOf:'2026-10-01',days:14}).minimum,8000);assert.equal(next.transactions.length,0);assert.equal(C.periodForecast(next,'2026-09').committed,1000);assert.equal(before.obligations[0].skipped,undefined);});
test('a skipped future generated occurrence remains cancelled after backup reload',()=>{const next=C.cancelScheduledOccurrence(fixture(),{id:'bill@2026-10-08',reason:'One-time cancellation'}),restored=C.clone(next);C.validateState(restored);assert.equal(C.scheduledEvents(restored,{from:'2026-10-08',to:'2026-10-08'})[0].skipped,true);assert.equal(C.scheduledEvents(restored,{from:'2026-10-15',to:'2026-10-15'})[0].skipped,false);assert.throws(()=>C.recordScheduled(restored,'bill@2026-10-08','2026-10-08'),/advance|unpaid/);});
test('paid history survives a dated stop, and future occurrences do not inherit old payment links',()=>{let s=C.recordScheduled(fixture(),'bill','2026-10-01');const future=C.scheduledEvents(s,{from:'2026-10-08',to:'2026-10-08'})[0];assert.equal(future.paid,false);assert.equal(future.transaction,undefined);s=C.stopSchedule(s,{id:'bill',effective:'2026-10-08',reason:'Subscription stopped'},'2026-10-07');const rows=C.scheduledEvents(s,{from:'2026-10-01',to:'2026-10-31'});assert.equal(rows.length,1);assert.equal(rows[0].paid,true);assert.equal(s.transactions.length,1);assert.equal(C.accountBalance(s,'bank','2026-10-07'),9000);});
test('future schedule replacement preserves old values and starts a separate dated template',()=>{const before=fixture(),next=C.replaceSchedule(before,{id:'bill',effective:'2026-10-08',reason:'New tariff',name:'New weekly bill',kind:'bill',amount:2000,account:'bank',recurrence:{unit:'weekly',interval:1}},'2026-10-07');const events=C.scheduledEvents(next,{from:'2026-10-01',to:'2026-10-15'});assert.deepEqual(events.map(o=>[o.date,o.amount]),[['2026-10-01',1000],['2026-10-08',2000],['2026-10-15',2000]]);assert.equal(next.obligations[0].amount,1000);assert.equal(next.obligations[1].replacesTemplate,'bill');assert.equal(next.operations.length,1);assert.equal(next.transactions.length,0);});
test('past replacements, unexplained cancellations and changes to paid occurrences are rejected',()=>{const s=fixture();assert.throws(()=>C.cancelScheduledOccurrence(s,{id:'bill',reason:''}),/Explain/);const paid=C.recordScheduled(s,'bill','2026-10-01');assert.throws(()=>C.cancelScheduledOccurrence(paid,{id:'bill',reason:'Undo actual payment'}),/unpaid/);assert.throws(()=>C.replaceSchedule(s,{id:'bill',effective:'2026-10-07',reason:'Changed'},'2026-10-07'),/future/);});
test('restoring a cancelled event preserves its explanation without creating money',()=>{const s=C.cancelScheduledOccurrence(fixture(),{id:'bill',reason:'Waived'});assert.throws(()=>C.recordScheduled(s,'bill','2026-10-01'),/unpaid/);const restored=C.restoreScheduledOccurrence(s,'bill');assert.equal(restored.obligations[0].skipReason,'Waived');assert.equal(restored.obligations[0].skipped,false);assert.equal(restored.transactions.length,0);assert.equal(checked(s,restored,'obligation-restore').obligations[0].skipped,false);});
test('cloud schedule changes retain the same old values and reject rewriting a paid template',()=>{const before=fixture(),stopped=C.stopSchedule(before,{id:'bill',effective:'2026-10-08',reason:'Stopped'},'2026-10-07');assert.equal(checked(before,stopped,'obligation-stop').obligations[0].cancelAfter,'2026-10-08');const forged=C.clone(stopped);forged.obligations[0].amount=9999;assert.throws(()=>checked(before,forged,'obligation-stop'),/dated future stop/);const replacement=C.replaceSchedule(before,{id:'bill',effective:'2026-10-08',reason:'New tariff',name:'Replacement',kind:'bill',amount:2000,account:'bank'},'2026-10-07');assert.equal(checked(before,replacement,'obligation-replace').obligations.length,2);replacement.obligations[1].date='2026-10-09';assert.throws(()=>checked(before,replacement,'obligation-replace'),/boundary/);});
test('cancelling a generated occurrence cannot change its original price through sync',()=>{const before=fixture(),next=C.cancelScheduledOccurrence(before,{id:'bill@2026-10-08',reason:'Waived'});assert.equal(checked(before,next,'obligation-skip').obligations.length,2);next.obligations[1].amount=9999;assert.throws(()=>checked(before,next,'obligation-skip'),/original schedule/);});
