import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,mutate,clone} from '../app/core.mjs';
import {diffEntities} from '../app/sync.mjs';
import {validateOperation} from '../server/validation.mjs';

function example(){const before=fresh(),after=mutate(before,'note-add',{},n=>n.notes.push({id:'n',title:'中文 العربية',body:'Private note',items:[]}));return {before,after,request:{workspace:before.id,operationId:crypto.randomUUID(),expectedVersion:0,type:'note-add',patches:diffEntities(before,after)}};}
test('server validator accepts a valid complete candidate without mutating the trusted snapshot',()=>{const {before,after,request}=example(),old=clone(before);const next=validateOperation(before,request);assert.deepEqual(next.notes,after.notes);assert.equal(next.seq,1);assert.equal(next.version,1);assert.deepEqual(before,old);});
test('server validator rejects wrong owner workspace, stale versions and envelope injection',()=>{const {before,request}=example();assert.throws(()=>validateOperation(before,{...request,workspace:'another'}),/workspace/);assert.throws(()=>validateOperation(before,{...request,expectedVersion:1}),/conflict/);assert.throws(()=>validateOperation(before,{...request,owner:'attacker'}),/envelope/);assert.throws(()=>validateOperation(before,{...request,operationId:'retry'}),/ID/);});
test('server validator rejects invalid financial records and reused sequences',()=>{const {before,request}=example();assert.throws(()=>validateOperation(before,{...request,patches:request.patches.filter(p=>p.collection!=='preferences')}),/sequence/);assert.throws(()=>validateOperation(before,{...request,patches:[...request.patches,{collection:'goals',key:'g',action:'put',value:{id:'g',name:'Bad target',target:-1,priority:1}}]}),/target/);});
test('server validator cannot inject fabricated historical or zero-amount ledger entries',()=>{const {before,request}=example();before.categories=[{id:'other',name:'Other',type:'variable'}];for(const historical of [true,false]){const t={id:'t',kind:'expense',seq:historical?0:1,date:'2026-10-06',amount:0,postings:[],historical};assert.throws(()=>validateOperation(before,{...request,patches:[...request.patches,{collection:'transactions',key:'t',action:'put',value:t}]}),/New transactions/);}});
test('server validator rejects duplicate patches and unsafe reservation keys',()=>{const {before,request}=example();assert.throws(()=>validateOperation(before,{...request,patches:[...request.patches,request.patches[0]]}),/Duplicate/);assert.throws(()=>validateOperation(before,{...request,patches:[...request.patches,{collection:'reservations',key:'__proto__',action:'put',value:{amount:1}}]}),/Unsafe/);});
