import {test} from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import * as C from '../app/core.mjs';
import {openStore,saveStore,loadStore,snapshots,saveDraft,loadDrafts,syncRecovery} from '../app/storage.mjs';
const read=(db,store,key)=>new Promise((resolve,reject)=>{const request=key===undefined?db.transaction(store).objectStore(store).getAll():db.transaction(store).objectStore(store).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const note=s=>C.mutate(s,'note-add',{},n=>n.notes.push({id:C.uid(),title:'Synthetic',body:'中文 العربية',items:[]}));
async function isolated(run){const previous=globalThis.indexedDB;globalThis.indexedDB=new IDBFactory();const db=await openStore();try{await run(db);}finally{db.close();if(previous===undefined)delete globalThis.indexedDB;else globalThis.indexedDB=previous;}}
test('state, queue and snapshots save atomically; acknowledged edits leave the queue',async()=>isolated(async db=>{const a=note(C.fresh());assert.equal(await saveStore(db,a,0),1);assert.equal((await read(db,'outbox')).length,1);const b=C.clone(a);b.operations[0].sync='synced';assert.equal(await saveStore(db,b,1),2);assert.equal((await read(db,'outbox')).length,0);assert.deepEqual((await snapshots(db))[0].state,a);assert.deepEqual((await loadStore(db)).state,b);}));
test('a stale save neither replaces records nor consumes its retained draft',async()=>isolated(async db=>{const a=note(C.fresh());await saveStore(db,a,0);const draft={id:'draft-test',form:{kind:'note'}};await saveDraft(db,draft);await assert.rejects(saveStore(db,note(a),0,draft.id),/Another tab/);assert.deepEqual((await loadStore(db)).state,a);assert.deepEqual(await loadDrafts(db),[draft]);assert.equal((await read(db,'outbox')).length,1);}));
test('reviewed restore preserves old queue for recovery and prevents stale or later replay',async()=>isolated(async db=>{const a=note(C.fresh());await saveStore(db,a,0);const restored=note(C.fresh());await saveStore(db,restored,1,null,{restore:true});assert.deepEqual((await loadStore(db)).state,restored);assert.equal((await read(db,'outbox')).length,0);const rows=await read(db,'current'),archive=rows.find(row=>Array.isArray(row.operations)&&row.workspace===a.id);assert.equal(archive.operations[0].id,a.operations[0].id);assert.equal((await read(db,'current','sync-hold')).workspace,restored.id);const recovery=await syncRecovery(db);assert.equal(recovery.automaticReplay,false);assert.equal(recovery.archives[0].operations[0].id,a.operations[0].id);assert.equal(recovery.hold.workspace,restored.id);await saveStore(db,note(restored),2);assert.equal((await read(db,'outbox')).length,0);assert.equal((await loadStore(db)).state.operations.length,2);}));

test('full pre-restore records survive rolling snapshot rotation even with an empty sync queue',async()=>isolated(async db=>{let original=note(C.fresh());original.operations.forEach(o=>o.sync='synced');await saveStore(db,original,0);const draft={id:'kept-draft',input:{title:'Unapplied'}};await saveDraft(db,draft);let restored=note(C.fresh());await saveStore(db,restored,1,null,{restore:true});for(let revision=2;revision<35;revision++){restored=note(restored);await saveStore(db,restored,revision);}const recovery=await syncRecovery(db);assert.equal(recovery.restores.length,1);assert.deepEqual(recovery.restores[0].state,original);assert.deepEqual(recovery.restores[0].operations,[]);assert.equal(recovery.restores[0].permanent,true);assert.ok((await snapshots(db)).some(row=>row.permanent&&row.state.id===original.id));assert.deepEqual(await loadDrafts(db),[draft]);assert.equal((await read(db,'outbox')).length,0);assert.deepEqual((await loadStore(db)).state,restored);}));
test('a stale restore cannot create a misleading retained archive or replace the current workspace',async()=>isolated(async db=>{const original=note(C.fresh());await saveStore(db,original,0);await assert.rejects(saveStore(db,C.fresh(),0,null,{restore:true}),/Another tab/);assert.equal((await syncRecovery(db)).restores.length,0);assert.deepEqual((await loadStore(db)).state,original);}));
