import {test} from 'node:test';
import assert from 'node:assert/strict';
import {supabaseAdapter} from '../server/supabase-adapter.mjs';
import * as C from '../app/core.mjs';
import * as S from '../app/sync.mjs';
const owner='11111111-1111-4111-8111-111111111111',config={url:'https://synthetic-project.supabase.co',publishableKey:'sb_publishable_SYNTHETIC',secretKey:'sb_secret_SYNTHETIC'};
test('identity uses the publishable key and user JWT, while private RPCs use only the secret API key',async()=>{const calls=[],adapter=supabaseAdapter({...config,fetchImpl:async(url,options)=>{calls.push({url,options});return Response.json(url.includes('/auth/')?{id:owner,is_anonymous:false,email:'not-retained@example.test'}:{workspace:'synthetic'});}});assert.deepEqual(await adapter.verifySession('synthetic-jwt'),{id:owner,is_anonymous:false});await adapter.store.read(owner,'synthetic');assert.equal(calls[0].options.headers.apikey,config.publishableKey);assert.equal(calls[0].options.headers.Authorization,'Bearer synthetic-jwt');assert.equal(calls[1].options.headers.apikey,config.secretKey);assert.equal(Object.hasOwn(calls[1].options.headers,'Authorization'),false);assert.equal(calls[1].options.redirect,'error');assert.deepEqual(JSON.parse(calls[1].options.body),{p_owner:owner,p_workspace:'synthetic'});});
test('invalid endpoints or misplaced keys cannot send credentials',()=>{let calls=0;const fetchImpl=()=>{calls++;};for(const url of ['http://synthetic-project.supabase.co','https://evil.example','https://user:pass@synthetic-project.supabase.co','https://synthetic-project.supabase.co/redirect'])assert.throws(()=>supabaseAdapter({...config,url,fetchImpl}),/endpoint/);assert.throws(()=>supabaseAdapter({...config,secretKey:config.publishableKey,fetchImpl}),/keys/);assert.equal(calls,0);});
test('unverified auth and anonymous users never become permanent actors',async()=>{for(const response of [Response.json({id:owner,is_anonymous:true}),Response.json({id:owner}),new Response('denied',{status:401})]){const adapter=supabaseAdapter({...config,fetchImpl:async()=>response});assert.equal(await adapter.verifySession('synthetic-jwt'),null);}});
test('network and database errors never echo credentials or raw server errors',async()=>{const adapter=supabaseAdapter({...config,fetchImpl:async()=>{throw new Error(config.secretKey+' private diagnostics');}});await assert.rejects(adapter.store.read(owner,'synthetic'),error=>error.message.includes('No edit')&&!error.message.includes(config.secretKey)&&!error.message.includes('diagnostics'));});
test('budget RPCs retain exact consent context and keep privileged credentials server-side',async()=>{const calls=[],adapter=supabaseAdapter({...config,fetchImpl:async(url,options)=>{calls.push({url,options});return Response.json({status:'reserved'});}}),requestId=crypto.randomUUID(),hash='a'.repeat(64);await adapter.ledger.reserve({owner,requestId,reservedMicroUsd:100,configurationHash:hash,workspaceDigest:hash,summaryDigest:hash,promptDigest:hash});await adapter.ledger.settle({owner,requestId,status:'uncertain',chargedMicroUsd:null});assert.ok(calls[0].url.endsWith('/plan_ai_reserve'));assert.deepEqual(JSON.parse(calls[0].options.body),{p_owner:owner,p_id:requestId,p_amount:100,p_configuration_hash:hash,p_workspace_digest:hash,p_summary_digest:hash,p_prompt_digest:hash});assert.deepEqual(JSON.parse(calls[1].options.body),{p_owner:owner,p_id:requestId,p_status:'uncertain',p_charged:null});for(const call of calls){assert.equal(call.options.headers.apikey,config.secretKey);assert.equal(call.options.headers.Authorization,undefined);}});
test('first-upload RPC uses only the private key and rechecks the complete reviewed payload',async()=>{
 const calls=[],adapter=supabaseAdapter({...config,fetchImpl:async(url,options)=>{calls.push({url,options});return Response.json({status:'initialized',version:1});}}),state=C.fresh(),records=S.entities(state),command={workspace:state.id,requestId:C.uid(),records,payloadDigest:await C.digest(S.canonicalJson(records))};
 await adapter.store.bootstrap(owner,command);assert.equal(calls.length,1);assert.ok(calls[0].url.endsWith('/plan_bootstrap_validated_workspace'));assert.equal(calls[0].options.headers.apikey,config.secretKey);assert.equal(calls[0].options.headers.Authorization,undefined);assert.deepEqual(JSON.parse(calls[0].options.body),{p_owner:owner,p_workspace:state.id,p_request:command.requestId,p_digest:command.payloadDigest,p_records:records});
 await assert.rejects(adapter.store.bootstrap(owner,{...command,payloadDigest:'a'.repeat(64)}),/changed/);assert.equal(calls.length,1);
});
