import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,clone,mutate} from '../app/core.mjs';
import {diffEntities,applyPatches,flushOperations,SyncConflict} from '../app/sync.mjs';
function transport(){let version=0;const ids=new Set();return {apply:async({operationId,expectedVersion})=>{if(ids.has(operationId))return {status:'duplicate',version};if(expectedVersion!==version)return {status:'conflict',version};ids.add(operationId);return {status:'applied',version:++version};},version:()=>version};}
test('sync changes individual records and retains original history',()=>{const before=fresh(),after=mutate(before,'note-add',{},n=>n.notes.push({id:'n',title:'Idea',body:'中文 العربية',items:[]}));const patches=diffEntities(before,after);assert.equal(patches.length,1);assert.equal(patches[0].collection,'notes');assert.deepEqual(applyPatches(before,patches).notes,after.notes);});
test('sync refuses hard deletion of records',()=>{const before=fresh();before.notes=[{id:'n',title:'Saved',body:'',items:[]}];const after=clone(before);after.notes=[];assert.throws(()=>diffEntities(before,after),/cannot delete/);});
test('retry after lost network response uses the same immutable operation ID',async()=>{const server=transport(),operations=[{id:'one',type:'note',patches:[]}];await flushOperations({workspace:'w',operations,remoteVersion:0,transport:server});const ack=[];const result=await flushOperations({workspace:'w',operations,remoteVersion:0,transport:server,onAck:async id=>ack.push(id)});assert.equal(result,1);assert.equal(server.version(),1);assert.deepEqual(ack,['one']);});
test('two devices changing the same version produce a reviewable conflict',async()=>{const server=transport();await flushOperations({workspace:'w',operations:[{id:'a',patches:[]}],remoteVersion:0,transport:server});let acknowledged=false;await assert.rejects(flushOperations({workspace:'w',operations:[{id:'b',patches:[]}],remoteVersion:0,transport:server,onAck:async()=>{acknowledged=true;}}),SyncConflict);assert.equal(acknowledged,false);assert.equal(server.version(),1);});
test('failed transport does not acknowledge or discard the queue',async()=>{let ack=0;const operations=[{id:'a',patches:[]}];await assert.rejects(flushOperations({workspace:'w',operations,remoteVersion:0,transport:{apply:async()=>{throw new Error('Offline');}},onAck:async()=>{ack++;}}),/Offline/);assert.equal(ack,0);assert.equal(operations.length,1);});
