import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
import * as S from '../app/sync.mjs';
import {createSyncHttpHandler} from '../server/sync-http.mjs';
const origin='https://plan.example.test',owner='11111111-1111-4111-8111-111111111111';
function setup(options={}){const state=C.fresh();state.version=1;const after=C.mutate(state,'note-add',{},s=>s.notes.push({id:'sample',title:'Synthetic',body:'',items:[]})),calls=[],verified=[];const snapshot={workspace:state.id,version:1,records:S.entities(state).map(r=>({...r,version:1})),operations:[]},operation={workspace:state.id,expectedVersion:1,operationId:crypto.randomUUID(),type:'note-add',patches:S.diffEntities(state,after)};const store={read:async(actor,id)=>{calls.push(['read',actor,id]);return C.clone(snapshot);},apply:async(actor,value)=>{calls.push(['apply',actor,value]);return {status:'applied',version:2};}};const verifySession=async token=>{verified.push(token);return token==='valid'?{id:owner,is_anonymous:false}:token==='anonymous'?{id:owner,is_anonymous:true}:null;};return {state,operation,calls,verified,store,handler:createSyncHttpHandler({origin,verifySession,store,...options})};}
function req(body,{headers={},url=origin+'/api/plan/sync',method='POST'}={}){return new Request(url,{method,headers:{origin,'sec-fetch-site':'same-origin',authorization:'Bearer valid','content-type':'application/json',...headers},...(method==='POST'?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});}
test('HTTP sync derives one permanent verified owner and returns private snapshots and atomic results',async()=>{const f=setup();const read=await f.handler(req({action:'read',workspace:f.state.id}));assert.equal(read.status,200);assert.equal((await read.json()).result.workspace,f.state.id);assert.equal(read.headers.get('cache-control'),'no-store, private');assert.equal(read.headers.get('access-control-allow-origin'),null);const write=await f.handler(req({action:'apply',request:f.operation}));assert.deepEqual(await write.json(),{action:'apply',result:{status:'applied',version:2}});assert.deepEqual(f.verified,['valid','valid']);assert.ok(f.calls.every(c=>c[1]===owner));});
test('cross-origin, wrong route/method, missing token and anonymous input never reach private storage',async()=>{const f=setup(),body={action:'read',workspace:f.state.id};for(const [options,status] of [[{headers:{origin:'https://attacker.test'}},403],[{headers:{origin:''}},403],[{headers:{'sec-fetch-site':'cross-site'}},403],[{url:origin+'/api/plan/sync?token=private'},404],[{url:'https://attacker.test/api/plan/sync'},404],[{method:'GET'},405],[{headers:{authorization:''}},401],[{headers:{authorization:'Bearer anonymous'}},401]])assert.equal((await f.handler(req(body,options))).status,status);assert.equal(f.calls.length,0);});
test('malformed input, owner injection and altered operations cannot post money or leak internal errors',async()=>{const f=setup();for(const body of ['{bad','[]',JSON.stringify({action:'read',workspace:f.state.id,owner:'attacker'})])assert.equal((await f.handler(req(body))).status,400);const denied=await f.handler(req({action:'apply',request:{...f.operation,owner:'attacker'}}));assert.equal(denied.status,422);assert.equal(JSON.stringify(await denied.json()).includes('attacker'),false);assert.equal(f.calls.some(c=>c[0]==='apply'),false);f.store.read=async()=>{throw new Error('secret-key private-account private-database');};const failed=await f.handler(req({action:'read',workspace:f.state.id}));assert.equal(failed.status,422);assert.equal((await failed.text()).includes('secret-key'),false);});
test('stale cloud versions return a conflict without invoking the write adapter',async()=>{const f=setup(),response=await f.handler(req({action:'apply',request:{...f.operation,expectedVersion:0}}));assert.equal(response.status,409);assert.deepEqual((await response.json()).result,{status:'conflict',version:1});assert.equal(f.calls.some(c=>c[0]==='apply'),false);});
test('body limits cover content type, compression, declared size, actual streamed bytes and slow input',async()=>{const f=setup({bodyTimeoutMs:20}),body={action:'read',workspace:f.state.id};for(const [headers,status] of [[{'content-type':'text/plain'},415],[{'content-encoding':'gzip'},415],[{'content-length':'2000001'},413],[{'content-length':'1'},400]])assert.equal((await f.handler(req(body,{headers}))).status,status);const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array(1_000_001));c.enqueue(new Uint8Array(1_000_001));c.close();}}),headers={origin,authorization:'Bearer valid','content-type':'application/json'};assert.equal((await f.handler(new Request(origin+'/api/plan/sync',{method:'POST',headers,body:stream,duplex:'half'}))).status,413);let cancelled=false;const slow=new ReadableStream({cancel(){cancelled=true;}});assert.equal((await f.handler(new Request(origin+'/api/plan/sync',{method:'POST',headers,body:slow,duplex:'half'}))).status,408);assert.equal(cancelled,true);assert.equal(f.calls.length,0);});
test('private HTTP wiring refuses wildcard, HTTP, path-bearing origins and absent adapters',()=>{for(const value of ['*','http://plan.example.test',origin+'/',origin+'/path','https://user:pass@plan.example.test'])assert.throws(()=>setup({origin:value}),/HTTPS app origin/);assert.throws(()=>setup({verifySession:null}),/verified session/);});
