import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
import * as S from '../app/sync.mjs';
import {syncService} from '../server/sync-service.mjs';
const owner='11111111-1111-4111-8111-111111111111';
function fixture(){const state=C.fresh(),after=C.mutate(state,'note-add',{},n=>n.notes.push({id:'n',title:'Synthetic',body:'',items:[]})),request={workspace:state.id,operationId:crypto.randomUUID(),expectedVersion:0,type:'note-add',patches:S.diffEntities(state,after)},calls=[];let snapshot={workspace:state.id,version:0,records:S.entities(state).map(r=>({...r,version:1})),operations:[]};snapshot.version=1;state.version=1;request.expectedVersion=1;return {state,request,calls,store:{read:async(actor,id)=>{calls.push(['read',actor,id]);return C.clone(snapshot);},apply:async(actor,command)=>{calls.push(['write',actor,command]);return {status:'applied',version:2};}},setSnapshot:s=>snapshot=s};}
const verifier=async token=>token==='valid'?{id:owner,is_anonymous:false}:token==='anonymous'?{id:owner,is_anonymous:true}:null;
test('unverified and anonymous sessions cannot access the privileged store',async()=>{const f=fixture(),service=syncService({verifySession:verifier,store:f.store});for(const token of ['', 'invalid','anonymous'])await assert.rejects(service.apply({token,request:f.request}),/permanent/);assert.equal(f.calls.length,0);});
test('the owner is derived from verified identity and body ownership injection is rejected',async()=>{const f=fixture(),service=syncService({verifySession:verifier,store:f.store});assert.deepEqual(await service.apply({token:'valid',request:f.request}),{status:'applied',version:2});assert.equal(f.calls[1][1],owner);await assert.rejects(service.apply({token:'valid',request:{...f.request,owner:'attacker'}}),/envelope/);assert.equal(f.calls.filter(c=>c[0]==='write').length,1);});
test('invalid financial edits and stale versions never reach the write adapter',async()=>{const f=fixture(),service=syncService({verifySession:verifier,store:f.store});const invalid={...f.request,patches:[...f.request.patches,{collection:'goals',key:'g',action:'put',value:{id:'g',name:'Invalid',target:-1,priority:1}}]};await assert.rejects(service.apply({token:'valid',request:invalid}),/target/);assert.deepEqual(await service.apply({token:'valid',request:{...f.request,expectedVersion:0}}),{status:'conflict',version:1});assert.equal(f.calls.some(c=>c[0]==='write'),false);});
test('lost-response replay matches immutable payload and audit survives hydration',async()=>{const f=fixture(),next=C.mutate(f.state,'note-add',{},n=>n.notes.push({id:'n',title:'Synthetic',body:'',items:[]}));f.setSnapshot({workspace:next.id,version:2,records:S.entities(next).map(r=>({...r,version:2})),operations:[{id:f.request.operationId,type:f.request.type,version:2,patches:f.request.patches,at:'2026-10-07T00:00:00Z'}]});const service=syncService({verifySession:verifier,store:f.store});assert.deepEqual(await service.apply({token:'valid',request:f.request}),{status:'duplicate',version:2});await assert.rejects(service.apply({token:'valid',request:{...f.request,type:'different'}}),/reused/);assert.equal(f.calls.some(c=>c[0]==='write'),false);const restored=S.hydrateSnapshot(await service.read({token:'valid',workspace:next.id}));assert.equal(restored.operations[0].id,f.request.operationId);assert.equal(restored.operations[0].sync,'synced');assert.deepEqual(restored.operations[0].patches,f.request.patches);});
test('uninitialized workspaces require explicit bootstrap rather than implicit upload',async()=>{const f=fixture();f.store.read=async()=>null;const service=syncService({verifySession:verifier,store:f.store});await assert.rejects(service.apply({token:'valid',request:f.request}),/initialize/);assert.equal(f.calls.length,0);});

test('a private adapter returning another workspace cannot leak or acknowledge its records',async()=>{const f=fixture(),wrong=C.fresh();f.setSnapshot({workspace:wrong.id,version:1,records:S.entities(wrong).map(r=>({...r,version:1})),operations:[]});const service=syncService({verifySession:verifier,store:f.store});await assert.rejects(service.read({token:'valid',workspace:f.state.id}),/different workspace/);await assert.rejects(service.apply({token:'valid',request:f.request}),/different workspace/);assert.equal(f.calls.some(c=>c[0]==='write'),false);});
