import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../app/core.mjs';
function state(){const s=C.fresh();s.accounts=[{id:'bank',name:'Bank',kind:'asset',currency:'CNY',opening:0,baselineDate:'2026-10-06',baselineSeq:0}];s.categories=[{id:'food',name:'Food',type:'variable'},{id:'transport',name:'Transport',type:'variable'},{id:'oneoff',name:'Other',type:'variable'}];s.budgets=[{id:'2026-09',key:'2026-09',salary:100000,alloc:{food:10000,transport:5000},locks:{}}];return s;}
test('split entries affect categories while posting the account once',()=>{let s=state();s=C.addTransaction(s,{kind:'expense',amount:30000,date:'2026-10-06',account:'bank',category:'oneoff',splits:[{category:'food',amount:20000},{category:'transport',amount:10000}]});assert.equal(C.accountBalance(s,'bank','2026-10-06'),-30000);assert.equal(C.periodForecast(s,'2026-09').spending,30000);assert.equal(C.expenseTotal(s,'2026-09'),30000);assert.equal(s.transactions.length,1);});
test('split amounts must exactly equal the total',()=>{assert.throws(()=>C.addTransaction(state(),{kind:'expense',amount:30000,date:'2026-10-06',account:'bank',splits:[{category:'food',amount:20000},{category:'transport',amount:9999}]}),/equal/);});
test('partial loan returns link actual cash to the original record, without assuming the rest',()=>{let s=state();s.outside=[{id:'loan',name:'Borrower',amount:100000,returned:0,date:'2026-09-01',kind:'loan'}];s=C.returnOutside(s,{id:'loan',amount:30000,account:'bank',date:'2026-10-06'});assert.equal(s.outside[0].returned,30000);assert.equal(C.accountBalance(s,'bank','2026-10-06'),30000);assert.equal(s.outside[0].returns[0].transaction,s.transactions[0].id);assert.throws(()=>C.returnOutside(s,{id:'loan',amount:80000,account:'bank',date:'2026-10-06'}),/outstanding/);assert.equal(C.periodForecast(s,'2026-10').income,100000);});
test('a no-interest debt pays off with a smaller final installment',()=>{const r=C.debtPayoff({balance:100000,payment:30000});assert.equal(r.months,4);assert.equal(r.rows.at(-1).paid,10000);assert.equal(r.interest,0);assert.equal(r.total,100000);});
test('correcting a linked return restores the outstanding amount without deleting history',()=>{let s=state();s.outside=[{id:'loan',name:'Borrower',amount:100000,returned:0,date:'2026-09-01',kind:'loan'}];s=C.returnOutside(s,{id:'loan',amount:30000,account:'bank',date:'2026-10-06'});s=C.reverseTransaction(s,s.transactions[0].id);assert.equal(s.outside[0].returned,0);assert.equal(C.accountBalance(s,'bank','2026-10-06'),0);assert.ok(s.outside[0].returns[0].reversedBy);});
test('interest is explicit and insufficient payments are infeasible',()=>{const r=C.debtPayoff({balance:100000,payment:100,annualRate:12});assert.equal(r.feasible,false);assert.ok(r.reason.includes('interest'));const okay=C.debtPayoff({balance:100000,payment:30000,annualRate:12});assert.equal(okay.feasible,true);assert.ok(okay.total>100000);assert.equal(okay.total-100000,okay.interest);});
test('ongoing ownership costs reduce capacity for later goals',()=>{const s=state();s.budgets[0].salary=100000;s.budgets[0].alloc={};s.goals=[{id:'car',name:'Car',target:100000,priority:1,recurringCost:50000},{id:'trip',name:'Trip',target:100000,priority:2}];s.reservations={car:0,trip:0};const p=C.planGoals(s,{asOf:'2026-10-06',periods:3});assert.equal(p.results[0].ready,'2026-11-14');assert.equal(p.results[1].ready,'2027-01-14');});
test('tampered transaction postings in backups are rejected',()=>{let s=state();s=C.addTransaction(s,{kind:'expense',amount:10000,date:'2026-10-06',account:'bank',category:'food'});s.transactions[0].postings[0].amount=100000;assert.throws(()=>C.validateState(s),/postings/);});
test('spending insights point to real evidence and honor corrections',()=>{let s=state();s=C.addTransaction(s,{kind:'expense',amount:20000,date:'2026-10-06',account:'bank',category:'food'});const insight=C.spendingInsights(s,'2026-09').find(x=>x.kind==='over-budget');assert.equal(insight.amount,10000);assert.deepEqual(insight.evidence,[s.transactions[0].id]);s=C.reverseTransaction(s,s.transactions[0].id);assert.ok(!C.spendingInsights(s,'2026-09').some(x=>x.kind==='over-budget'));});
