import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createZenTextProvider} from '../server/zen-provider.mjs';
const args={summary:{currency:'CNY',units:'minor units'},prompt:'Explain the assumptions.',maxInputTokens:1000,maxOutputTokens:100,maxSteps:1};
const receipt=()=>({id:'synthetic',model:'deepseek-v4.1-flash',choices:[{finish_reason:'stop',message:{content:'Synthetic answer',reasoning_content:'Hidden reasoning must not be returned'}}],usage:{prompt_tokens:42,completion_tokens:18,total_tokens:60,completion_tokens_details:{reasoning_tokens:12}}});
function fixture({data=receipt(),status=200,count=42,confirmCharge}={}){const calls=[];const provider=createZenTextProvider({apiKey:'synthetic-not-a-real-key',countInputTokens:()=>count,confirmCharge,fetchImpl:async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});}});return {provider,calls};}
test('a bounded provider sends one request to the official endpoint and keeps the credential server-side',async()=>{const f=fixture(),result=await f.provider(args);assert.equal(f.calls.length,1);assert.equal(f.calls[0].url,'https://opencode.ai/zen/v1/chat/completions');assert.equal(f.calls[0].options.redirect,'error');const payload=JSON.parse(f.calls[0].options.body);assert.equal(payload.max_tokens,100);assert.equal(payload.stream,false);assert.equal(payload.messages.length,2);assert.equal(result.chargedMicroUsd,null);assert.equal(result.result.text,'Synthetic answer');assert.equal(result.result.usage.reasoningTokens,12);assert.ok(!JSON.stringify(result).includes('Hidden reasoning'));assert.ok(!JSON.stringify(result).includes('synthetic-not-a-real-key'));});
test('an absent verified tokenizer or input above the bound cannot reach the provider',async()=>{assert.throws(()=>createZenTextProvider({apiKey:'synthetic'}),/tokenizer/);const f=fixture({count:1001});await assert.rejects(f.provider(args),/input token bound/);assert.equal(f.calls.length,0);await assert.rejects(f.provider({...args,maxSteps:2}),/exactly one/);assert.equal(f.calls.length,0);});
test('provider rejection and transport failure never retry or expose raw errors',async()=>{const f=fixture({status:403,data:{error:{message:'secret synthetic error'}}});await assert.rejects(f.provider(args),/HTTP 403/);assert.equal(f.calls.length,1);let calls=0;const provider=createZenTextProvider({apiKey:'synthetic',countInputTokens:()=>42,fetchImpl:async()=>{calls++;throw new Error('secret network content');}});await assert.rejects(provider(args),e=>!e.message.includes('secret')&&/uncertain charge/.test(e.message));assert.equal(calls,1);});
test('truncated answers, wrong models and excess billable reasoning/output fail verification',async()=>{for(const mutate of [d=>d.choices[0].finish_reason='length',d=>d.model='another-model',d=>d.usage.completion_tokens_details.reasoning_tokens=19,d=>{d.usage.completion_tokens=101;d.usage.total_tokens=143;},d=>d.choices[0].message.tool_calls=[{}]]){const data=receipt();mutate(data);const f=fixture({data});await assert.rejects(f.provider(args),/complete text|usage|reasoning/);assert.equal(f.calls.length,1);}});
test('token usage alone remains unconfirmed until a trusted charge verifier settles it',async()=>{const f=fixture({confirmCharge:async value=>{assert.equal(value.usage.completion_tokens,18);return 35;}});assert.equal((await f.provider(args)).chargedMicroUsd,35);const invalid=fixture({confirmCharge:()=>1.5});await assert.rejects(invalid.provider(args),/charge/);});
test('oversized provider responses are bounded without exposing their content',async()=>{const data=receipt();data.choices[0].message.content='x'.repeat(200001);const f=fixture({data});await assert.rejects(f.provider(args),/could not be verified/);});
test('malformed UTF-8 cannot silently corrupt a displayed provider answer',async()=>{
  const text=JSON.stringify(receipt()).replace('Synthetic answer','REPLACE'),parts=text.split('REPLACE'),before=new TextEncoder().encode(parts[0]),after=new TextEncoder().encode(parts[1]),bytes=new Uint8Array(before.length+1+after.length);bytes.set(before);bytes[before.length]=255;bytes.set(after,before.length+1);
  const provider=createZenTextProvider({apiKey:'synthetic',countInputTokens:()=>42,fetchImpl:async()=>new Response(bytes)});await assert.rejects(provider(args),/could not be verified/);
});
test('one deadline covers token counting, network, streamed answer and charge verification without retries',async()=>{
  let release,calls=0;const delayed=createZenTextProvider({apiKey:'synthetic',timeoutMs:5,countInputTokens:()=>new Promise(resolve=>release=resolve),fetchImpl:async()=>{calls++;return Response.json(receipt());}});
  await assert.rejects(delayed(args),/timed out/);release(42);await Promise.resolve();assert.equal(calls,0);
  let cancelled=false;const stream=createZenTextProvider({apiKey:'synthetic',timeoutMs:5,countInputTokens:()=>42,fetchImpl:async()=>{calls++;return new Response(new ReadableStream({pull(){return new Promise(()=>{});},cancel(){cancelled=true;}}));}});
  await assert.rejects(stream(args),/timed out/);assert.equal(cancelled,true);assert.equal(calls,1);
  const charge=createZenTextProvider({apiKey:'synthetic',timeoutMs:5,countInputTokens:()=>42,fetchImpl:async()=>{calls++;return Response.json(receipt());},confirmCharge:()=>new Promise(()=>{})});
  await assert.rejects(charge(args),/timed out/);assert.equal(calls,2);
});
