import {useState} from 'react';
import type {Workspace,CommitEdit,Reconciliation} from '../types';
import {engine,cashLabel} from '../domain';
export function Accounts({state,commit,busy}:{state:Workspace;commit:CommitEdit;busy:boolean}){
  const [page,setPage]=useState(0),[filter,setFilter]=useState(''),asOf=engine.today(state.timezone);
  const history=state.reconciliations.filter(r=>!filter||r.account===filter).slice().reverse(),currentPage=Math.min(page,Math.max(0,Math.ceil(history.length/100)-1));
  const submit=async(form:HTMLFormElement,account:string)=>{const input=Object.fromEntries(new FormData(form));const success=await commit('reconcile',{account,...input},s=>engine.reconcile(s,{account,date:String(input.date),balance:engine.money(input.balance),note:String(input.note)}) as Workspace);if(success)form.reset();};
  const add=async(form:HTMLFormElement)=>{const input=Object.fromEntries(new FormData(form));const success=await commit('account-add',input,s=>{const name=String(input.name).trim();if(!name)throw new Error('Enter an account name.');return engine.mutate(s,'account-add',input,(n:Workspace)=>{n.accounts.push({id:engine.uid(),name,kind:String(input.kind) as 'asset'|'liability',currency:n.currency,opening:null,baselineDate:engine.today(n.timezone),baselineSeq:n.seq});}) as Workspace;});if(success)form.reset();};
  return <><h1>Check your balances.</h1><p>Enter the balance you observed. Every check retains the expected balance and its difference for review. A reviewed difference is not assigned to a spending category.</p><div className="grid">{state.accounts.map(account=><section className="card" key={account.id}><h2>{account.name}</h2><p>{account.kind==='liability'?'Debt account: owed balances are negative.':'Cash account'}</p><div className="number">{cashLabel(state,engine.accountBalance(state,account.id))}</div><p>{account.verified?'Last checked':'Not verified'} · {account.baselineDate}</p>{account.limit!==undefined&&<p>Credit limit: {cashLabel(state,account.limit)}</p>}<form onSubmit={e=>{e.preventDefault();void submit(e.currentTarget,account.id);}}><fieldset disabled={busy}><label>Observed balance<input name="balance" type="number" step="0.01" required/></label><label>Check date<input name="date" type="date" min={account.baselineDate} max={asOf} defaultValue={asOf} required/></label><label>Statement note<input name="note" maxLength={10000}/></label><button className="button primary">Save balance check</button></fieldset></form></section>)}</div><section className="card"><h2>Add an account</h2><p>A new account has no verified balance until you check it. Its name does not create income or savings.</p><form aria-label="Add account" onSubmit={e=>{e.preventDefault();void add(e.currentTarget);}}><fieldset disabled={busy}><label>Account name<input name="name" required maxLength={300}/></label><label>Account type<select name="kind"><option value="asset">Bank / cash / savings</option><option value="liability">Debt / credit</option></select></label><button className="button primary">Add account</button></fieldset></form></section><section className="card"><h2>Balance-check history</h2><label>History account<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="">All accounts</option>{state.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><p>{history.length} checks · page {currentPage+1} of {Math.max(1,Math.ceil(history.length/100))}</p><ul className="list">{history.slice(currentPage*100,(currentPage+1)*100).map(r=><BalanceReview key={r.id} state={state} record={r} commit={commit} busy={busy}/>)}</ul>{!history.length&&<p>No balance checks yet.</p>}<div className="row"><button className="button quiet" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Previous checks</button><button className="button quiet" disabled={(currentPage+1)*100>=history.length} onClick={()=>setPage(currentPage+1)}>Next checks</button></div></section></>;
}
function BalanceReview({state,record:r,commit,busy}:{state:Workspace;record:Reconciliation;commit:CommitEdit;busy:boolean}){
  const review=async(form:HTMLFormElement)=>{const input=new FormData(form),note=String(input.get('note')||''),transactions=input.getAll('evidence').map(String);await commit('balance-review',{id:r.id,note,transactions},s=>engine.reviewReconciliation(s,{id:r.id,note,transactions}) as Workspace);};
  const evidence=state.transactions.filter(t=>t.account===r.account||t.toAccount===r.account).slice().sort((a,b)=>b.date.localeCompare(a.date)||b.seq-a.seq).slice(0,100);
  return <li><strong>{state.accounts.find(a=>a.id===r.account)?.name}</strong><p>{r.date} · observed {cashLabel(state,r.balance)} · expected {cashLabel(state,r.expected??null)}</p><p>{r.difference===null?'First baseline':'Difference: '+cashLabel(state,r.difference)} · {r.status}</p>{r.note&&<p>{r.note}</p>}{r.review&&<><p>{r.review.note}</p><p>{r.review.transactions.length} supporting entries · explanation saved {r.review.at}</p></>}{r.status==='unresolved'&&<details><summary>Explain this difference</summary><p>The observed balance and original difference stay intact. Supporting entries help explain it; they are not automatically changed.</p><form aria-label="Review balance difference" onSubmit={e=>{e.preventDefault();void review(e.currentTarget);}}><fieldset disabled={busy}><label>Why the difference is understood<input name="note" required maxLength={10000}/></label><details><summary>Link supporting entries (optional)</summary><p>Showing the latest 100 entries for this account. Older entries can be investigated in activity.</p>{evidence.map(t=><label className="check" key={t.id}><input type="checkbox" name="evidence" value={t.id}/>{t.date} · {t.note||t.kind} · {cashLabel(state,t.amount)}</label>)}</details><button className="button primary">Mark difference reviewed</button></fieldset></form></details>}</li>;
}
