import {useState,type FormEvent} from 'react';
import type {Workspace,Scenario} from '../types';
import {PlanningChecks} from './PlanningChecks';
import {engine,forecast,cashLabel} from '../domain';
export function Planner({state}:{state:Workspace}){
  const [scenario,setScenario]=useState<Scenario>({mode:'budget',extraExpense:0,incomeChange:0,protection:state.settings.monthlyProtection}),[error,setError]=useState('');
  const result=forecast(state,scenario);
  function compare(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);try{const mode=String(fields.get('mode'));if(!['budget','history','conservative'].includes(mode))throw new Error('Choose a forecast baseline.');const next:Scenario={mode:mode as Scenario['mode'],extraExpense:engine.money(fields.get('extra')),incomeChange:engine.money(fields.get('income')),protection:engine.money(fields.get('protection'))};forecast(state,next);setScenario(next);setError('');}catch(e){setError(e instanceof Error?e.message:'Check the scenario amounts.');}}
  return <><h1>Give your goals a path.</h1><p>Every purchase draws from the same pool. These comparisons do not change your records.</p><section className="card"><form onSubmit={compare}><div className="formgrid"><label>Forecast baseline<select name="mode" defaultValue={scenario.mode}><option value="budget">My budget</option><option value="history">Budget + recorded history</option><option value="conservative">Conservative: spending +15%</option></select></label><label>Extra cost each period<input name="extra" type="number" step="0.01" min="0" defaultValue={scenario.extraExpense/100} required/></label><label>Income change each period<input name="income" type="number" step="0.01" defaultValue={scenario.incomeChange/100} required/></label><label>Protected saving each period<input name="protection" type="number" step="0.01" min="0" defaultValue={scenario.protection/100} required/></label></div><button className="button primary">Compare schedule</button></form>{error&&<p role="alert">{error}</p>}</section>
    {result.warnings.map(w=><div className="notice" key={w}>{w.replace(/(\d+) minor units/g,(_,n:string)=>cashLabel(state,Number(n)))}</div>)}
    <section className="card"><h2>Your goals, together</h2><div className="tablewrap"><table><thead><tr><th>Goal</th><th>Remaining target</th><th>Forecast funding</th><th>Desired date</th></tr></thead><tbody>{result.results.map(g=><tr key={g.id}><td>{g.name}</td><td>{cashLabel(state,g.target)}</td><td>{g.ready||'Not achievable in this horizon'}</td><td className={g.late?'negative':''}>{g.deadline||'Flexible'}</td></tr>)}</tbody></table></div>{!result.results.length&&<p>Add a purchase goal in Goals to start.</p>}</section>
    <section className="card"><h2>Why these dates?</h2><ul className="list">{result.assumptions.map(a=><li key={a}>{a}</li>)}</ul></section>
  <PlanningChecks key={state.id+'-'+state.version+'-'+state.seq} state={state}/></>;
}
