import {useState} from 'react';
import type {Workspace,GoalForecast} from '../types';
import {engine,cashLabel} from '../domain';
type SpendingResult=ReturnType<typeof engine.goalSpendingPath>;
export function SpendingPath({state}:{state:Workspace}){
  const [result,setResult]=useState<SpendingResult|null>(null),[error,setError]=useState('');
  const goals=state.goals.filter(g=>!g.archived&&!g.protected&&g.kind!=='saving'),categories=state.categories.filter(c=>!c.archived&&c.type==='variable'&&c.id!=='oneoff'),asOf=engine.today(state.timezone);
  return <section className="card"><h2>Could spending less bring a goal closer?</h2><p>Compare a smaller future allowance in one flexible category. Existing bills, locked allowances, other goals and protected savings stay in the calculation. This does not change your budget.</p><form aria-label="Goal spending path" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);try{setResult(engine.goalSpendingPath(state,{id:String(fields.get('goal')),category:String(fields.get('category')),deadline:String(fields.get('deadline'))}));setError('');}catch(e){setResult(null);setError(e instanceof Error?e.message:'Check the goal, category and date.');}}}><div className="formgrid"><label>Goal for spending comparison<select name="goal" required>{goals.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Flexible spending category<select name="category" required>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Spending comparison deadline<input name="deadline" type="date" min={asOf} required/></label></div><button className="button primary" disabled={!goals.length||!categories.length}>Calculate a spending path</button></form>{error&&<p role="alert">{error}</p>}{result&&<><p><strong>{result.feasible?result.spendingReduction?'Reduce '+result.categoryName+' by up to '+cashLabel(state,result.spendingReduction)+' in each future period':'Fits these assumptions without reducing spending':('reason' in result?result.reason:'Review the assumptions')}</strong></p>{result.feasible&&'allowances' in result&&<><p>Forecast funding: {result.ready}. Choose an allowance you can maintain, then check daily purchase timing before paying.</p><div className="tablewrap"><table><thead><tr><th>Financial period</th><th>Current allowance</th><th>Compared allowance</th><th>Reduction</th></tr></thead><tbody>{result.allowances.map(p=><tr key={p.key}><td>{p.key}{p.locked?' · Locked':''}</td><td>{cashLabel(state,p.before)}</td><td>{cashLabel(state,p.after)}</td><td>{cashLabel(state,p.reduction)}</td></tr>)}</tbody></table></div></>}{'plan' in result&&<><h3>Other goals by this date</h3><ul className="list">{result.plan.results.filter((g:GoalForecast)=>g.id!==result.id).map((g:GoalForecast)=><li key={g.id}>{g.name} · {g.ready?'Forecast funding: '+g.ready:'Still unfunded by this date'}</li>)}</ul></>}{'plan' in result&&result.plan.warnings.map(w=><p className="notice" key={w}>{w.replace(/(\d+) minor units/g,(_,n:string)=>cashLabel(state,Number(n)))}</p>)}<ul className="list">{result.assumptions.map(a=><li key={a}>{a}</li>)}</ul></>}</section>;
}
