import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const app=new URL('../app/',import.meta.url),frontend=new URL('../frontend/',import.meta.url);
const files=['style.css','ui.mjs','core.mjs','storage.mjs','sync.mjs','edit-session.mjs','offline.mjs','report.mjs','backup.mjs','react/main.js','react/LICENSES.txt'];
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const source=await Promise.all(files.map(async name=>({name,bytes:await readFile(new URL(name,app))})));
const native=await readFile(new URL('native-shell.html',frontend),'utf8'),react=await readFile(new URL('react-shell.html',frontend),'utf8');
const metadata=await Promise.all(['manifest.json','icon.svg'].map(name=>readFile(new URL(name,app))));
const fingerprint=hash(Buffer.concat([...source.map(f=>f.bytes),...metadata,Buffer.from(native+react),await readFile(new URL(import.meta.url))]));
const base=`./assets/${fingerprint}`;
const release=new URL(`assets/${fingerprint}/`,app);await mkdir(new URL('react/',release),{recursive:true});
for(const file of source)await writeFile(new URL(file.name,release),file.bytes);
await writeFile(new URL('index.html',app),native.replaceAll('%ASSET_BASE%',base));
await writeFile(new URL('react.html',app),react.replaceAll('%ASSET_BASE%',base));
const entries=[];
for(const name of ['index.html','react.html','manifest.json','icon.svg',...files.map(name=>`assets/${fingerprint}/${name}`)])entries.push({path:`./${name}`,sha256:hash(await readFile(new URL(name,app)))});
entries.unshift({path:'./',sha256:entries[0].sha256});
const cache=`plan-v2-shell-${fingerprint}`;
const worker=`// Generated by scripts/build-shell.mjs. Public shell only; never private records or API responses.
const CACHE=${JSON.stringify(cache)},SHELL=${JSON.stringify(entries)};
const entryFor=request=>{const url=new URL(request.url);if(request.method!=='GET'||url.origin!==self.location.origin)return null;return SHELL.find(entry=>new URL(entry.path,self.location.href).pathname===url.pathname);};
self.addEventListener('install',event=>event.waitUntil((async()=>{
  try{const responses=await Promise.all(SHELL.map(async entry=>{
    const url=new URL(entry.path,self.location.href),response=await fetch(url,{cache:'no-store',redirect:'error'});
    if(!response.ok)throw new Error('Incomplete public app release.');
    const digest=await crypto.subtle.digest('SHA-256',await response.clone().arrayBuffer()),actual=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
    if(actual!==entry.sha256)throw new Error('App release changed while installing.');
    return {url,response};
  }));const cache=await caches.open(CACHE);for(const item of responses)await cache.put(item.url,item.response);
  }catch(error){await caches.delete(CACHE);throw error;}
})()));
// Wait for existing tabs to close naturally. Never reload a form or force an update.
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('plan-v2-shell-')&&key!==CACHE).map(key=>caches.delete(key))))));
self.addEventListener('fetch',event=>{
  const entry=entryFor(event.request);if(!entry)return;
  event.respondWith((async()=>{const cache=await caches.open(CACHE),response=await cache.match(new URL(entry.path,self.location.href));return response||new Response('This PLAN release is not installed offline. Reconnect and reopen the app.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});})());
});
`;
await writeFile(new URL('sw.js',app),worker);
console.log(`Built a verified public shell: ${fingerprint.slice(0,12)} (${entries.length} assets).`);
